### ISSUE TITLE
how to get Agent-Computer Interface (ACI),    readme  only teach to run terminal Interface ?  how to get aci ?

### ISSUE THREAD

**Issue by jinpengchina** [princeton-nlp/SWE-agent#103]
how to get Agent-Computer Interface (ACI),    readme  only teach to run terminal Interface ?  how to get aci ?

**Comment by klieret** [comment]
I'm not sure if I understand the question correctly, but there currently only is a command line interface for this project

**Comment by jinpengchina** [comment]
The interface at 38 seconds in this video;      https://www.youtube.com/watch?time_continue=39&v=CeMtJ4XObAM&embeds_referring_euri=https%3A%2F%2Fswe-agent.com%2F&embeds_referring_origin=https%3A%2F%2Fswe-agent.com&source_ve_path=MTM5MTE3LDI4NjY2&feature=emb_logo

**Comment by klieret** [comment]
This is from [https://sweagent.com](https://swe-agent.com/demo). Currently we only have a command line interface and a viewer to view trajectories

**Comment by CodeCreator** [comment]
Hi @jinpengchina, thank you for your interest! We are currently still working on open-sourcing the web viewer from the video!
