### ISSUE TITLE
how to get Agent-Computer Interface (ACI), readme only teach to run terminal Interface ? how to get aci ? 

### ISSUE THREAD

**Issue by jinpengchina** [princeton-nlp/SWE-agent#104]
how to get Agent-Computer Interface (ACI), readme only teach to run terminal Interface ? how to get aci ? ; The interface at 38 seconds in this video; https://www.youtube.com/watch?time_continue=39&v=CeMtJ4XObAM&embeds_referring_euri=https%3A%2F%2Fswe-agent.com%2F&embeds_referring_origin=https%3A%2F%2Fswe-agent.com&source_ve_path=MTM5MTE3LDI4NjY2&feature=emb_logo

**Comment by klieret** [comment]
See #103
