### ISSUE TITLE
[Question] Can SWE-Agent be used to debug my personal projects?

### ISSUE THREAD

**Issue by dattasid** [princeton-nlp/SWE-agent#106]
I have noticed that ChatGPT already understands the codebase of the repositories that are in SWE-Bench. Of course, it will not know anything about my personal projects.

Will SWE-Agent still work by feeding the directory structure and relevant code snippets to ChapGPT?

**Comment by CodeCreator** [comment]
SWE-agent should be capable of interacting and navigating in new repositories. Performance will depend on many factors, e.g. difficulty of the issue, how well-maintained the codebase is, etc..

The best way to find out is to try it out! Please let us know how it goes! I will close the issue for now.
