### ISSUE TITLE
keys.cfg required when running from swe-agent-run docker image

### ISSUE THREAD

**Issue by tarunn2799** [princeton-nlp/SWE-agent#109]
### Describe the bug

I can't run the quickstart example provided in the repo. It says it can't find the keys.cfg file in the docker image. But I am passing the keys as env variables in the docker run command with the `-e` flag. Its not showing up in the config that gets printed out when you run run.py either. The env variables aren't being used. Thanks!

### Steps/Code to Reproduce

What I tried to run

```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
  -e GITHUB_TOKEN="my token" \
  -e OPENAI_API_KEY="token" \
  sweagent/swe-agent-run:latest \
  python run.py --image_name=sweagent/swe-agent:latest \
  --model_name gpt4 \
  --data_path "github issue url" \
  --config_file config/default_from_url.yaml  --skip_existing=False
```

### Expected Results

That it runs

### Actual Results

```
Traceback (most recent call last):
  File "/app/run.py", line 288, in <module>
    main(args)
  File "/app/run.py", line 88, in main
    agent = Agent("primary", args.agent)
  File "/app/sweagent/agent/agents.py", line 186, in __init__
    self.model = get_model(args.model, args.config._commands + args.config.subroutine_types)
  File "/app/sweagent/agent/models.py", line 706, in get_model
    return OpenAIModel(args, commands)
  File "/app/sweagent/agent/models.py", line 225, in __init__
    cfg = config.Config(os.path.join(os.getcwd(), "keys.cfg"))
  File "/usr/local/lib/python3.9/site-packages/config/__init__.py", line 707, in __init__
    self.load_file(stream_or_path, kwargs.get('encoding'))
  File "/usr/local/lib/python3.9/site-packages/config/__init__.py", line 815, in load_file
    with io.open(path, encoding=encoding or 'utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/keys.cfg'
```

### System Information

MacOS M1 running docker locally.

**Comment by yuanzhixiang** [comment]
I have this problem also

**Comment by klieret** [comment]
Thanks for reporting! This might indeed be a bug.

**Comment by tarunn2799** [comment]
Thank you! 

So I tried going the conda setup way, created my keys.cfg and placed it in the root folder of the SWE-agent repo folder. setup.sh ran properly for me and my docker image has been created locally. How do I run this now?

**Comment by klieret** [comment]
If you go the conda route, simply continue following the steps there (see quickstart and benchmarking).

The bug currently only affects running with the `swe-agent-run` docker image

**Comment by yuanzhixiang** [comment]
> Thank you!
> 
> So I tried going the conda setup way, created my keys.cfg and placed it in the root folder of the SWE-agent repo folder. setup.sh ran properly for me and my docker image has been created locally. How do I run this now?

You can test this command

docker run --rm -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /xxxx/keys.cfg:/app/keys.cfg \
  -e GITHUB_TOKEN="xxxx" \
  -e OPENAI_API_KEY="xxxx" \
  sweagent/swe-agent-run:latest \
  python run.py --image_name=sweagent/swe-agent:latest \
  --model_name gpt4 \
  --data_path xxxx \
  --config_file config/default_from_url.yaml  --skip_existing=False

**Comment by klieret** [comment]
In this case you don't need the `-e` options. Actually this is a good workaround for this issue right now. Let me update the instructions.

**Comment by klieret** [comment]
Let's use the `-v /xxxx/keys.cfg:/app/keys.cfg` workaround for now. I'll open a separate issue to not require the file in the future.
