### ISSUE TITLE
Question: Where's the code fix produced by SWE-agent?

### ISSUE THREAD

**Issue by jswift24** [princeton-nlp/SWE-agent#112]
### Describe the bug

I got SWE-agent to run the sample command from readme.md. It looks like the execution succeeded, but where did it put the fix?

### Steps/Code to Reproduce

`python run.py --model_name gpt4   --data_path https://github.com/pvlib/pvlib-python/issues/1603   --config_file config/default_from_url.yaml --image_name=sweagent/swe-agent:latest`

### Expected Results

Would like to see success/failure message at the end of the trace
If success, would like to see a pointer to the code fix (in python)
If it skipped the test issue, it should say so too and then I'd expect the trace to be a lot shorter...

### Actual Results

Got the trace attached. Also a new local folder
`...../SWE-agent/trajectories/alonb/gpt4__pvlib__pvlib-python__default_from_url__t-0.00__p-0.95__c-3.00__install-1`

[execution trace.txt](https://github.com/princeton-nlp/SWE-agent/files/14894666/execution.trace.txt)

### System Information

WSL on Windows

**Comment by klieret** [comment]
Currently, you can get the fix as follows:

```python
import json

# Open the .jsonl file and read line by line
with open('/path/to/your/trajectory/all_preds.jsonl', 'r') as file:
    for line in file:
        data = json.loads(line)
        print(data["model_patch"])
```

We'll add a feature to save the patch separately in a nicer format with #41

**Comment by klieret** [comment]
If you're working on your own repo, you can also add the `--open_pr` flag to open a PR

**Comment by klieret** [comment]
As of the latest development version, we separately save the patches in the `trajectories/.../patches` directory

**Comment by jswift24** [comment]
Thanks. 
Feature request: I noticed that SWE-agent clones the repo before attempting a fix. Would be great to access that cloned version with the fixes, so that it can be tested, deployed, etc.

**Comment by klieret** [comment]
there's the `--open-pr` option to open a PR if certain conditions are being met

**Comment by jswift24** [comment]
Users may want to test locally before opening the PR, particularly since they didn't write the code.

For example, I'd like to try to SWE-agent on some of the feature requests on your list, but I'm not sure the PRs will be high quality enough to send in.

**Comment by klieret** [comment]
then you can manually apply patches with `git apply trajectories/.../patches`. There's also #57 which is probably similar to what you want.

**Comment by jswift24** [comment]
Thanks! Didn't know about `git apply`. I upvoted #57.
