### ISSUE TITLE
Mixing GPT4 for analysis and Claude 3 for code generation 

### ISSUE THREAD

**Issue by Am0stafa** [princeton-nlp/SWE-agent#121]
### Describe the feature

Ok, so GPT 4 is the king when it comes to reasoning but it is lazy and Claude 3 opus is the king when it comes to coding. So what we can do is use GPT for analyzing and proposing a solution and Claude to implement it. This will make it more powerful. By making LLMs work together this will make them soo powerful

### Potential Solutions

I really didn’t dig deep into how to implement it but I am interested to start doing that and hopefully, if I get a green flag after further discussion I can go ahead and start implementing this change as a contribution.

**Comment by ofirpress** [comment]
If you implement this and show us numbers on the dev set we might consider this, otherwise we don't have the bandwidth currently to try such features

**Comment by ofirpress** [comment]
(We did try something similar during development and it didn't really improve perf...)

**Comment by Am0stafa** [comment]
Yeah regarding that I am not actually sure if two LLMs solving a problem together how accurate will that be but given that you tried it seems that it would be a meaningful contribution.
Btw i am ramy a senior computer science student and a researcher I did a research on applied  cryptography by using secure multi party computing. I really believe in this project and I want to make a meaningful contribution so can you guide me on where to focus?
