### ISSUE TITLE
Add live benchmark tracking graph to readme.md

### ISSUE THREAD

**Issue by distbit0** [princeton-nlp/SWE-agent#139]
### Describe the feature

It would be cool to be able to see how the benchmark perfromance of swe-agent improves over time in response to contributions. Perhaps this could be done in such a way as to allow anyone to observe it by publishing a graph of benchmark results re-calculated every week or so, to start off with.

This would also encourage other devin-esque agent projects to put more emphasis on their swe-bench results, allowing for potential contributors and users to more easily decide which projects to spend their time looking into and contributing to. 

### Potential Solutions

n/a

**Comment by klieret** [comment]
I agree this is nice, but running over the whole dataset is quite expensive and time consuming, so I don't think this will be done automatically. However, I do think that we can improve a lot in terms of how easy it is to get the benchmarks and to include them in a project. Definitely on the agenda!
