### ISSUE TITLE
Azure ecosystem support

### ISSUE THREAD

**Issue by cpendery** [princeton-nlp/SWE-agent#14]
It would be great if the agent supported the Azure ecosystem both through supporting Azure OpenAI & through pulling Azure Devops stories/tasks instead of Github issues.

**Comment by ofirpress** [comment]
If you submit a PR we could consider it but as this is a repo for quick & efficient research I don't think that this will be on our priority list for now.

**Comment by cpendery** [comment]
@ofirpress that's fair, I'm happy to submit a set of PRs for it
