### ISSUE TITLE
Claude 3 benchmarks

### ISSUE THREAD

**Issue by EwoutH** [princeton-nlp/SWE-agent#15]
It would be very useful to have some Claude 3 benchmarks using SWE-Agent.

![IMG_1200](https://github.com/princeton-nlp/SWE-agent/assets/15776622/a85a74cb-5771-4025-9640-8e3d22d53e9a)

Since Claude 3 Opus performs better than GPT-4 using RAG, there’s a fair chance that will also be the case when using SWE-Agents, right?

Also really curious how Claude 3 Sonnet and Haiku perform, since they not that far behind Opus (and way cheaper).

**Comment by ofirpress** [comment]
We have some initial numbers on swebench.com . See https://twitter.com/OfirPress/status/1775226081575915661

We'll have more soon.
