### ISSUE TITLE
Ensure docker is running

### ISSUE THREAD

**Issue by berrazuriz1** [princeton-nlp/SWE-agent#159]
Ensure docker is running
Docker desktop > Settings > Advanced > `Allow the default Docker socket to be used (requires password)` needs to be enabled.

_Originally posted by @timothycarambat in https://github.com/princeton-nlp/SWE-agent/issues/20#issuecomment-2035675121_

**Comment by berrazuriz1** [comment]
This should be in the README. I was stuck like an hour on this. Is a silly settings, but it never occur to me to check it until I saw the closed issue

**Comment by timothycarambat** [comment]
The only reason it didnt take me an hour to debug is because i had this issue before on another project 😆

**Comment by klieret** [comment]
Thanks! I've added it to the readme in a new section.
