### ISSUE TITLE
win11报错了

### ISSUE THREAD

**Issue by benlan96** [princeton-nlp/SWE-agent#160]
### Describe the issue

INFO     Saved trajectory to trajectories/root/gpt4__397179459__iMaoTai-reserve__default_from_url__t-0.00__p-0.95__c-3.00__install-1/397179459__iMaoTai-reserve-i16.traj
INFO     Saved predictions to trajectories/root/gpt4__397179459__iMaoTai-reserve__default_from_url__t-0.00__p-0.95__c-3.00__install-1/all_preds.jsonl
Traceback (most recent call last):
  File "/app/run.py", line 144, in main
    save_patch(traj_dir, instance_id, info)
  File "/app/run.py", line 271, in save_patch
    patch_output_file.write_text(model_patch)
  File "/usr/local/lib/python3.9/pathlib.py", line 1283, in write_text
    raise TypeError('data must be str, not %s' %
TypeError: data must be str, not NoneType
WARNING  ❌ Failed on 397179459__iMaoTai-reserve-i16: data must be str, not NoneType
INFO     Beginning environment shutdown...
INFO     Agent container stopped
DEBUG    Starting container with command: docker run -i --rm --name sweagent-swe-agent-latest-50e6fc6a45 sweagent/swe-agent:latest /bin/bash -l -m
INFO     🌱 Environment Initialized

### Suggest an improvement to documentation

INFO     Saved trajectory to trajectories/root/gpt4__397179459__iMaoTai-reserve__default_from_url__t-0.00__p-0.95__c-3.00__install-1/397179459__iMaoTai-reserve-i16.traj
INFO     Saved predictions to trajectories/root/gpt4__397179459__iMaoTai-reserve__default_from_url__t-0.00__p-0.95__c-3.00__install-1/all_preds.jsonl
Traceback (most recent call last):
  File "/app/run.py", line 144, in main
    save_patch(traj_dir, instance_id, info)
  File "/app/run.py", line 271, in save_patch
    patch_output_file.write_text(model_patch)
  File "/usr/local/lib/python3.9/pathlib.py", line 1283, in write_text
    raise TypeError('data must be str, not %s' %
TypeError: data must be str, not NoneType
WARNING  ❌ Failed on 397179459__iMaoTai-reserve-i16: data must be str, not NoneType
INFO     Beginning environment shutdown...
INFO     Agent container stopped
DEBUG    Starting container with command: docker run -i --rm --name sweagent-swe-agent-latest-50e6fc6a45 sweagent/swe-agent:latest /bin/bash -l -m
INFO     🌱 Environment Initialized

**Comment by ofirpress** [comment]
We don't currently have bandwidth to provide support for Windows. Please use WSL which other people have been successfully using
