### ISSUE TITLE
error AttributeError: 'NoneType' object has no attribute 'prompt_tokens'

### ISSUE THREAD

**Issue by xiangpingjiang** [princeton-nlp/SWE-agent#168]
### Describe the bug

I use the docker setup, and follow the example in readme.
but got the error AttributeError: 'NoneType' object has no attribute 'prompt_tokens'
![image](https://github.com/princeton-nlp/SWE-agent/assets/45722758/12943f1d-cf21-49fc-b8f0-6d249e5a74f3)

### Steps/commands/code to Reproduce

```
set my keys.cfg file , then 

docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
  # replace /xxxx/keys.cfg with the paths to your keys
  -v /xxxx/keys.cfg:/app/keys.cfg \
  # replace with your architecture, either arm64 or amd64
  --platform=linux/arm64 \
  sweagent/swe-agent-run:latest \
  python run.py --image_name=sweagent/swe-agent:latest \
  # the rest of the command as shown in the quickstart/benchmarking section,
  # for example to run on a specific github issue
  --model_name gpt4 \
  --data_path https://github.com/pvlib/pvlib-python/issues/1603 \
  --config_file config/default_from_url.yaml  --skip_existing=False
```

### Error message/results

```
Traceback (most recent call last):
  File "/app/run.py", line 136, in main
    info, trajectory = agent.run(
  File "/app/sweagent/agent/agents.py", line 645, in run
    thought, action, output = self.forward(
  File "/app/sweagent/agent/agents.py", line 373, in forward
    thought, action, output = self.forward_with_error_check(observation, state)
  File "/app/sweagent/agent/agents.py", line 513, in forward_with_error_check
    output = self.forward_model(observation, state)
  File "/app/sweagent/agent/agents.py", line 427, in forward_model
    return self.model.query(self.local_history)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/app/sweagent/agent/models.py", line 270, in query
    input_tokens = response.usage.prompt_tokens
AttributeError: 'NoneType' object has no attribute 'prompt_tokens'
```

### System Information

ubuntu , docker

### Checklist

- [X] I have copied the full command/code that I ran
- [X] I have copied the **full** log file/error message that was the result (if applicable)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code))

**Comment by klieret** [comment]
Hmm, strange. Just to double check: Are you sure the OpenAI key was set correctly (though that should fail with another error message).

I'll follow up later with a small script that could help us gather more information about this issue.

**Comment by xiangpingjiang** [comment]
hello @klieret 
I use this project https://github.com/PawanOsman/ChatGPT  as my LLM, and I changed the OPENAI_API_BASE_URL in keys.cfg file 

In the log ,it seems the call to llm got good response

**Comment by klieret** [comment]
I see. Then it's quite likely that the response from that project doesn't have `usage.prompt_tokens` implemented. In this case, there's nothing we can do. For the correct evaluation of the cost of the call, we need to have these statistics.

I think this is on you or on the [PawanOsman/ChatGPT](https://github.com/PawanOsman/ChatGPT) to implement a workaround for this. If you are fine with forking of this project, you could just overwrite `input_tokens = response.usage.prompt_tokens` to some value of your choosing.
