### ISSUE TITLE
Support Gab.ai API tokens

### ISSUE THREAD

**Issue by OrcVole** [princeton-nlp/SWE-agent#169]
### Describe the feature

OpenAI and Anthropic API tokens are already supported. 
Please also include support for e.g. Grok and Gab.ai (Arya)

### Potential Solutions

Create a generic API token section which can (using examples provided) with mimal edits be used to support AI from other AI companies, or self-hosted AI running at a home-office.

**Comment by klieret** [comment]
There are PRs for groq #108  #134. 

Generally, only very big models show useful performance with SWE-agent. 

Feel free to open a PR if you really want to have a certain model supported (though it might make more sense to work on #64), but I will close this as an issue.
