### ISSUE TITLE
Verify that proper demonstrations are supplied when running with additional installation flags.

### ISSUE THREAD

**Issue by klieret** [princeton-nlp/SWE-agent#171]
swe-agent running on swe-bench  issue should use 3rd demo
swe-agent running with github URL should use 1st demo

**Comment by ofirpress** [comment]
and swe-agent running with github URL + install script should use 3rd demo. we'll need to have @carlosejimenez confirm this later

**Comment by klieret** [comment]
Indeed, this currently seems to be incorrect, it chooses the 3rd demo (already installed) for the from github URL
