### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by luketchang** [princeton-nlp/SWE-agent#18]
The `swe-agent/agent/` and `swe-agent/environment/` links (as highlighted in the below screenshot) in the [Inference](https://github.com/princeton-nlp/SWE-agent?tab=readme-ov-file#-inference-) section of the readme are stale and return 404 pages. They were likely rendered stale when the top level `agent` and `environment` directories were moved under the `sweagent` directory.

Current path (incorrect): princeton-nlp/SWE-agent/blob/main/agent

Correct path: princeton-nlp/SWE-agent/tree/main/sweagent/agent

<img width="714" alt="Screenshot 2024-04-03 at 12 26 38 PM" src="https://github.com/princeton-nlp/SWE-agent/assets/32170738/5c7cc076-e072-4d41-bc91-babd7390074c">

**Comment by klieret** [comment]
Thanks for the report. Should be fixed with #6
