### ISSUE TITLE
exec /usr/local/bin/python: exec format error

### ISSUE THREAD

**Issue by heming79** [princeton-nlp/SWE-agent#180]
### Describe the bug

 docker logs  45263f126f61 
 exec /usr/local/bin/python: exec format error

### Steps/commands/code to Reproduce

docker run  -dit -v /var/run/docker.sock:/var/run/docker.sock   -v /data/heming/SWE-agent/keys.cfg:/app/keys.cfg --platform=linux/arm64   sweagent/swe-agent-run:latest   /usr/local/bin/python run.py --image_name=sweagent/swe-agent:latest   --model_name gpt4   --data_path https://github.com/pvlib/pvlib-python/issues/1603   --config_file config/default_from_url.yaml  --skip_existing=False

### Error message/results

 exec /usr/local/bin/python: exec format error

### System Information

ubuntu

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran
- [X] I have copied the **full** log file/error message that was the result (if applicable)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
Are you sure you're on `arm64`? I suspect you're on `amd64`.

**Comment by klieret** [comment]
@heming79 Did my comment solve the issue? Would be good to know so that other people who run in the same issue can see it
