### ISSUE TITLE
Unit test `models.py`

### ISSUE THREAD

**Issue by klieret** [princeton-nlp/SWE-agent#185]
Help us unit test the rest of `models.py`! Not the most glorious work, but very useful and appreciated!

Please carefully read the following notes:

* The goal is to increase coverage with as simple a test as possible
* The test must not use any credits or require credentials, i.e., you need to mock the relevant classes
* If you can test multiple models at once (in a parameterized fashion), all the better
* It's fine not to test every single line or raised exception, we're looking for the most "stupid" tests to get started
* There is already an example of [testing the OpenAI model](https://github.com/princeton-nlp/SWE-agent/blob/main/tests/test_models.py)
* Note that Mixtral might currently be broken (see #135)

**Comment by klieret** [comment]
@mikanfactory You mentioned you're working on this, right? Then let me assign it to you so that we don't get concurrent submissions :)

**Comment by mikanfactory** [comment]
@klieret Yes, I am working on it, so please assign it to me!
