### ISSUE TITLE
Add easy web based usage

### ISSUE THREAD

**Issue by curtcox** [princeton-nlp/SWE-agent#191]
### Describe the feature

A lower barrier to entry would enhance the adoption and usefulness of the project. Consider the following scenarios that a repo owner might want:
- Adding a link to the repo that users could follow to an instance pre-configured for working on the repo.
- Adding a link to an issue that users could follow to an instance configured to work the issue.

These links could be added manually or by bots.

### Potential Solutions

There are lots of potential options for where instances might run -- Replit, Colab, Github, ...
The important thing is that more people will have the time and ability to use SWE-agent for working issues if doing so is as simple as possible. That is true even if they need to have a paid account somewhere to use the link.

**Comment by klieret** [comment]
There's #84 with some leads. Generally, the project still has brittle parts, so "magic" applications are still a bit down the road.
