### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by andr0s** [princeton-nlp/SWE-agent#203]
### Describe the issue

I don't get it from the readme file. Can it work on private github repositories? If yes, would be nice to add some information in the readme file (i.e. where to put the github access token etc.)

Also what about support for bitbucket?

**Comment by klieret** [comment]
There currently is no support for bitbucket and I'm hesitant to put it. Instead, once #43 is merged, you will simply be able to run on local clones of repository.

**However**: You should already be able to run on private gh repos. github keys goes to `keys.cfg` as explained in the keys section of the readme.
