### ISSUE TITLE
Adding a support for Cohere API (new Command-R model)

### ISSUE THREAD

**Issue by adam2am** [princeton-nlp/SWE-agent#204]
### Describe the feature

Hey, I would like to suggest support for integrating additional language model API
- Cohere API (recent Command-R model with amazing retrieval-augmented generation)

This model recently got into the top 10 AI language models according to benchmarks like https://chat.lmsys.org/ and provide capabilities complementary to OpenAI's models. Particularly, people are saying it compelling for its strong RAG using its embeddings.

Would be amazing if you consider adding it!

### Potential Solutions

-

**Comment by ofirpress** [comment]
We will add support for something like LiteLLM therefore this issue will be deprecated. Closing
