### ISSUE TITLE
Improve formatting of console outputs with `rich`

### ISSUE THREAD

**Issue by klieret** [princeton-nlp/SWE-agent#208]
Currently, we mostly just use `logging.info` to output most parts of the trajectory. However, since we also save the trajectories, we might focus on making the output pretty and easy to understand instead. `rich` provides some very nice ways to display structured information. 

Also see #205

**Comment by ofirpress** [comment]
If we're gonna make the terminal interface nicer, I think we should also make it into a 2-pane view like we're thinking of making for the website. On the left only thoughts and actions, and on the right pane a "terminal view" with the actions interleaved with environment output. I think that would make stuff easier to see (right now it scrolls by too fast).

Not super urgent though.

**Comment by klieret** [comment]
That would be very cool, but I'm against it:

* Harder to implement
* Probably doesn't mix well with other logging calls/print statements without catching them
* Problematic for people who use `tmux` or other means of having multiple terminals side-by-side
* Can't easily copied/redirected to log file for debugging purposes

Probably could address some of these things, but I don't think it's worth it

**Comment by ofirpress** [comment]
ok, I wasn't aware of how complicated this would be.

so just do whatever improvements you were planning for the terminal, and then for the super nice & comfortable viewing experience we will have the browser view
