### ISSUE TITLE
Logs from SWE-Agent running on SWE-Bench

### ISSUE THREAD

**Issue by harrytormey** [princeton-nlp/SWE-agent#21]
First off, I'd like to say thank you so much for publishing SWE-bench and SWE-agent. I was wonder is their anywhere that has the logs from running SWE-Bench/SWE-ENG evaluation are posted? I am working on some langchain scripts to categorize and groups bugs/features that are being used to evaluate the models/agents and I'd like to dig into what issues fail or succeeded. 

I noticed on a previous [issue](https://github.com/princeton-nlp/SWE-bench/issues/23) @carlosejimenez provide links to generated results from Claude and GPTs. Is there something similar available but for the logs resulting from evaluation? Thanks so much in advance.

**Comment by ofirpress** [comment]
We'll release this soon, along with a preprint describing the SWE-agent system.

**Comment by ofirpress** [comment]
Update: all logs are here: https://github.com/swe-bench/experiments/tree/main/evaluation/test/20240402_sweagent_gpt4
