### ISSUE TITLE
[Under Discussion] Live Web UI

### ISSUE THREAD

**Issue by ofirpress** [princeton-nlp/SWE-agent#213]
We should have a frontend for being able to initiate runs, see their results in real time, and be able to view previous runs.

We should at first build an MVP that just runs on each user’s computer but eventually I’d like to be able to host this globally at swe-agent.com to allow people to initiate runs from there and view other people’s runs. Just keep that in mind, no need to implement this now. 

**How it will look:**

The initial screen should ask you for your GitHub token (optional) and then either your openAI key or anthropic key.

Then it should let you input:
1. the URL (github) or path to a local repository  and
2. either let you input some bug description text OR a URL linking to an issue in that repo that is already open. 

Then you click on the SWE-agent button and it starts the run.

**Here’s how the interface should look during an agent run:**

I think it should have 2 columns. The left column should show the <thought , action> outputs from the LM, and the right column should show the environment input commands and output.

So at timestep 9 it should look like: (scrollbar cursors should be at bottom)
 

<img width="608" alt="image" src="https://github.com/princeton-nlp/SWE-agent/assets/20109662/fd239526-3b41-40ab-9d8a-041d84ff4abb">

Let’s use Flask and nextjs or react

I think that eventually I'd like the UI to get the tokens in as they come from the GPT API (streaming) but the initial version does not need to have this.

I think we still need to finish other API changes in the swe-agent core before we can really start working on this but there's lots of external interest so I wanted to make this document public.

**Comment by adzcai** [comment]
What's the progress on this looking like? I'd be happy to contribute!

**Comment by linyudoa** [comment]
That's a good idea, I found one PR working on this _Locally hosted web UI #61_, but the latest update was 2 weeks ago.

**Comment by klieret** [comment]
#61 doesn't use flask but rather does "`os.system`" calls. This isn't optimal. I've started to play around with creating a small flask server, see #240, however, this is currently blocked due to issues with threading (see note in #240).

**Comment by ofirpress** [comment]
implemented in #321  yay :)
