### ISSUE TITLE
Support for Gitlab

### ISSUE THREAD

**Issue by cforce** [princeton-nlp/SWE-agent#220]
### Describe the feature

Please allow to use Gitlab as source for bug issues and push merge requests to its git repo as provided fix

### Potential Solutions

API for issues https://docs.gitlab.com/ee/api/issues.html.

**Comment by ofirpress** [comment]
We just don't have bandwidth for this right now. Local repos will be fully supported soon so you can just download your gitlab repo and use that. Thanks
