### ISSUE TITLE
Add support for Gemini models

### ISSUE THREAD

**Issue by NimJay** [princeton-nlp/SWE-agent#222]
### Describe the feature

* This is a feature request to add support for Google's Gemini models.
* I'm mainly creating this GitHub issue to first check if the owners of this repository are open to having Gemini support. :)
    * (I personally would want to try out this repo using Google's Gemini models.)

### Potential Solutions

* This changes would be similar to:
    * https://github.com/princeton-nlp/SWE-agent/pull/207
    * [Commit adding Ollama support](https://github.com/princeton-nlp/SWE-agent/commit/67fee842cd984a78b1e94f7be11705c3c351f0b4)
* See [Python Gemini client library example here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/generative_ai/gemini_pro_basic_example.py#L32).
* See source code for [GenerativeModel class here](https://github.com/googleapis/python-aiplatform/blob/f05924d6bbd9e609f4ca98cdef7ab5a504672e58/vertexai/generative_models/_generative_models.py#L98)

### Related documentation
* [cloud.google.com - Model API reference for Generative AI](https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/overview)

**Comment by ofirpress** [comment]
Yup, this would be great to have, we welcome contributions on this.

**Comment by klieret** [comment]
@NimJay Could you check if we could add the new model via [`litellm`](https://github.com/BerriAI/litellm)? We're slowly starting to accumulate a lot of models in `models.py` and perhaps slowly migrating some of them to use `litellm` might allow us to simplify (also see #64). For the models that are used in the paper, we need to be extra careful to replicate the cost function etc., so let's perhaps test this for new models first.

Disclaimer: I haven't looked too closely at `litellm`, so feel free to let me know if this doesn't seem like the right way to approach this.

**Comment by ofirpress** [comment]
We're going to add support for something like LiteLLM therefore this issue will be deprecated. Closing.
