### ISSUE TITLE
SWE-agent as a github action or bot

### ISSUE THREAD

**Issue by kripper** [princeton-nlp/SWE-agent#23]
Automatically process SWE-agent repo issues.
Investing effort in this more complex feature will accelerate/leverage future development of SWE-agent itself.

**Comment by ezzcodeezzlife** [comment]
A github action to easily copy to other repos would be great 👍

**Comment by klieret** [comment]
There's #84, but note that this is dangerous because of potentially escalating costs without further safeguards.

**Comment by zachblume** [comment]
sweep.dev has a really nice getting started workflow:
- Authorize sweep.dev access to your github repos
- Add a "sweep" label to any existing repo
- Title any new issue "Sweep: "

A similar workflow with the security params thought through would be great --> is there a github security feature to restrict certain kinds of issue manipulation to the maintainers only that SWE-agent could hook into and be safe by default?

**Comment by ofirpress** [comment]
I think this could be a really cool addition. We welcome contributions here. I also registered the github username @swe-agent so we could use that for this.
