### ISSUE TITLE
Failed to load the GITHUB_TOKEN from keys.cfg

### ISSUE THREAD

**Issue by huangjingcai** [princeton-nlp/SWE-agent#233]
### Describe the bug

Follow the README steps：
1.  [Install Docker](https://docs.docker.com/engine/install/), then start Docker locally.
2.  [Install Miniconda](https://docs.anaconda.com/free/miniconda/miniconda-install/), then create the swe-agent environment with conda env create -f environment.yml
3.  Activate using conda activate swe-agent.
4.  Run ./setup.sh to create the swe-agent docker image.
5.  Create a keys.cfg file at the root of this repository and fill in the following.

I have do this things above. But when I exec the run.py, it said  
'/usr/local/Caskroom/miniconda/base/envs/swe-agent/lib/python3.9/site-packages/ghapi/core.py:102: UserWarning: Neither GITHUB_TOKEN nor GITHUB_JWT_TOKEN found: running as unauthenticated
  else: warn('Neither GITHUB_TOKEN nor GITHUB_JWT_TOKEN found: running as unauthenticated')'

### Steps/commands/code to Reproduce

the keys.cfg file:
<img width="1679" alt="image" src="https://github.com/princeton-nlp/SWE-agent/assets/3855873/0b910b21-7ea1-44f8-9d3b-2471cb29add9">

and exec the command:
python run.py --model_name gpt4 \
  --data_path https://github.com/pvlib/pvlib-python/issues/1603 \
  --config_file config/default_from_url.yaml

### Error message/results

[swe.log](https://github.com/princeton-nlp/SWE-agent/files/14986020/swe.log)

### System Information

MacOS 12.7.4  Intel core
python 3.9

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran
- [X] I have copied the **full** log file/error message that was the result (if applicable)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
Curious, I just went through all the ghapi calls in the code and it seems fine. Will investigate later with a private repo, then it should fail without the token.

**Comment by klieret** [comment]
Hmm, everything runs fine for me with a private repo. Really not sure where this warning comes from. Can you try setting the token as an env variable with `export GITHUB_TOKEN="your gh token"` and seeing if it recognizes that? Also, can you double check that you're on the newest version?

**Comment by klieret** [comment]
Closing for lack of updates. Feel free to comment to reopen.

**Comment by constantOut** [comment]
<img width="852" alt="Screenshot 2024-05-23 at 15 01 04" src="https://github.com/princeton-nlp/SWE-agent/assets/30386571/d47842b1-8610-4773-8eb0-5042b81228c9">

Same issue, it doesn't use provided token, doesn't touch my repo ignoring data_path specified. 
And instead wastes my money on something related to

```
         (Open file: /sqlfluff__sqlfluff/src/sqlfluff/rules/L003.py)                                                                                                                                                                          
         (Current directory: /sqlfluff__sqlfluff)  
```
I think it should at least fail...

**Comment by klieret** [comment]
The github from `keys.cfg` are being used. @constantOut please open a bug report if you think something is not working as it should be.
