### ISSUE TITLE
gpt-4 leaking "rest of the code remains unchanged"

### ISSUE THREAD

**Issue by michaelneale** [princeton-nlp/SWE-agent#235]
### Describe the bug

![image](https://github.com/princeton-nlp/SWE-agent/assets/14976/f5469a78-57e4-468f-9a3a-6388e73e093f)
Successfully opening a PR (strong start to the code change) but (and this is likely GPT4) then ends up with what is a truncated change (gpt4 sometimes needs a lot of coaxing to not be lazy)

### Steps/commands/code to Reproduce

```python run.py --model_name gpt4 --data_path https://github.com/TBD54566975/tbdex-example-android/issues/13 --config_file config/default_from_url.yaml --open_pr --per_instance_cost_limit 9.0```

### Error message/results

Would expect it to have left more of the code unchanged (but readme was helpful as was earlier part of the change)

### System Information

MacOS M1

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran
- [X] I have copied the **full** log file/error message that was the result (if applicable)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
Thanks for reporting :) . I'm gonna mark this as `enhancement`, because this is GPT4's fault, so there's no immediate fix (but perhaps some prompt engineering). If this happened often, we could of course add some more code to address it. I'll talk to the rest of the team about this.

**Comment by ofirpress** [comment]
I don't know that we have a way to solve this. You could maybe delete all comments from the agent? Anyways I think for now this is relatively minor. As the base models get better these issues should go away.

**Comment by michaelneale** [comment]
yep - I thought as much, so often I have begged GPT4 (even opus from anthropic) to not do this... they are getting better. Feel free to close this as "time" may heal this

**Comment by ofirpress** [comment]
Ok let's close this for now
