### ISSUE TITLE
[Feature request] Support adding features

### ISSUE THREAD

**Issue by kripper** [princeton-nlp/SWE-agent#24]
Instead of only fixing issues, consider also adding new features (process issues describing feature requests).

This will accelerate/leverage the development of SWE-Agent itself and provide new real test cases.

Consider taking a look at GPT-Pilot and Meta-GPT.

**Comment by 0xdevalias** [comment]
> Consider taking a look at GPT-Pilot and Meta-GPT.

Links for convenience:

- https://github.com/Pythagora-io/gpt-pilot
  - > The first real AI developer
- https://github.com/geekan/MetaGPT
  - > The Multi-Agent Framework: First AI Software Company, Towards Natural Language Programming
