### ISSUE TITLE
`TARGETARCH` not set on some OS/docker setups

### ISSUE THREAD

**Issue by mspronesti** [princeton-nlp/SWE-agent#245]
### Describe the issue

Following the [setup with Conda instructions](https://github.com/princeton-nlp/SWE-agent?tab=readme-ov-file#-setup-with-conda-developer-version) of the README, I ran into an issue running `./setup.py` which traces back to the build of `swe.Dockerfile`. 

Specifically, it seems that the build arg `TARGETARCH` is never passed, thus `getconda.sh` exits with "unknown architecture detected?"

### Suggest an improvement to documentation

This should suffice.

```diff
diff --git a/setup.sh b/setup.sh
index faa0c31..3cea813 100755
--- a/setup.sh
+++ b/setup.sh
@@ -3,8 +3,13 @@
 # bash strict mode
 set -euo pipefail
 
+if [ "$#" -ne 1 ]; then
+    echo "Usage: ./setup.sh [aarch64|arm64|amd64|x86_64]"
+    exit 1
+fi
+
 echo "Setting up docker image for swe-agent..."
-docker build -t sweagent/swe-agent:latest -f docker/swe.Dockerfile .
+docker build -t sweagent/swe-agent:latest -f docker/swe.Dockerfile --build-arg TARGETARCH=$1 .
 
 echo "Setting up docker image for evaluation..."
 docker build -t sweagent/swe-eval:latest -f docker/eval.Dockerfile .
```

Example of usage: `./setup.py amd64`.

However, since I couldn't find any other issue reporting this, it could be a mistake on my part rather than a real issue. Hence why I am not opening a PR yet. Did anybody run into the same error?

**Comment by klieret** [comment]
Hmm, according to https://docs.docker.com/reference/dockerfile/#automatic-platform-args-in-the-global-scope, `TARGETARCH` should be set automatically (to `uname -m`). When you run `uname -a` on your system, what's the output? 

Also, could you run 
```
export BUILDKIT_PROGRESS=plain
./setup.sh
```

and run again? There should be output of `getconda.sh`:

```bash
arch=$1
echo "arch", $arch
```

so we can see what's going on.

Also, what's the exact error message that you had? (it should also print `$arch`)

**Comment by mspronesti** [comment]
@klieret  Here's the output I get
```shell
arch,
unknown architecture detected?
```

Here's the output of `uname -a`
```bash
Linux elle 5.15.0-101-generic #111~20.04.1-Ubuntu SMP Mon Mar 11 15:44:43 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by klieret** [comment]
Yup, it's set automatically for me (on OSX with docker 20.10.20). It also seems to work on Linux in github actions.

But it's enough to know that it doesn't work on _some_ systems. How about we just do 

```bash
# TARGETARCH should be set automatically on most (but not all) systems, see
# https://github.com/princeton-nlp/SWE-agent/issues/245
docker build -t sweagent/swe-agent:latest -f docker/swe.Dockerfile --build-arg TARGETARCH=$(uname -m)
```

**Comment by mspronesti** [comment]
Yep, that would work fine!
