### ISSUE TITLE
Hello, how can I specify my openai_base_URL instead

### ISSUE THREAD

**Issue by yxl23** [princeton-nlp/SWE-agent#26]
Hello, how can I specify my openai_base_URL instead

**Comment by klieret** [comment]
Could you elaborate?

**Comment by 0xdevalias** [comment]
Googling for `OPENAI_BASE_URL`, it sounds like this may commonly be used to proxy the API/similar:

- https://github.com/openai/openai-python/issues/1214
  - https://github.com/openai/openai-python#configuring-the-http-client

It sounds like it can be configured as an env var that will presumably be picked up by the underlying `openai` library.

`SWE-agent` also allows config via `keys.cfg`:

- https://github.com/princeton-nlp/SWE-agent#-setup-

Searching the repo for `keys.cfg` gives the following references:

- https://github.com/search?q=repo%3Aprinceton-nlp%2FSWE-agent%20keys.cfg&type=code
  - https://github.com/princeton-nlp/SWE-agent/blob/6c9ebf0ea8a263806b276da7ba3b1eda1f4a9475/sweagent/environment/swe_env.py#L86-L92
  - https://github.com/princeton-nlp/SWE-agent/blob/6c9ebf0ea8a263806b276da7ba3b1eda1f4a9475/sweagent/agent/models.py

From those code samples, it looks like `keys.cfg` only defines certain well-known keys that are explicitly read from that file by name; and they seem to only be API tokens/access keys, so doesn't seem like the right place to support something like `OPENAI_BASE_URL`.

So I would say that just exporting the env var in your shell environment is likely the best way to achieve this.

**Comment by klieret** [comment]
> It sounds like it can be configured as an env var that will presumably be picked up by the underlying openai library.

Thanks! Then let me close this :)
