### ISSUE TITLE
Implement Support for OpenRouter

### ISSUE THREAD

**Issue by AxDSan** [princeton-nlp/SWE-agent#261]
### Describe the feature

# SWE-Agent: Adding Support for OpenRouter 

## Overview

OpenRouter is a platform that provides access to various language models, similar in concept to LiteLM. While it would be beneficial to also integrate LiteLM in the future, this effort primarily focuses on enabling the use of OpenRouter models within SWE-Agent.

## OpenRouter Docs
https://openrouter.ai/docs

## Motivation

OpenRouter has gained traction as a versatile language model provider, offering access to a diverse range of models from different sources.

## Implementation

The main changes reside in the `models.py` file, located at `SWE-agent/sweagent/agent/models.py`. This file handles the integration of different language model providers within this project.

### Potential Solutions

Implement OpenRouter

**Comment by klieret** [comment]
@AxDSan  Given your comment in #266, should we close this in favor of https://github.com/princeton-nlp/SWE-agent/issues/64 ?

**Comment by AxDSan** [comment]
Totally! ✨

**Comment by alexx-ftw** [comment]
How's possible this is not yet implemented? Seems like a crucial feature to have
