### ISSUE TITLE
Support Deepinfra API

### ISSUE THREAD

**Issue by EwoutH** [princeton-nlp/SWE-agent#266]
### Describe the feature

Deepinfra is currently one of the cheapest API providers of LLM inference (together with groq see #108), which makes it interesting to support their API. They currently have the [cheapest](https://deepinfra.com/pricing) OpenChat, mixtral and Llama 3 inference token pricing available.

Having more API providers supported also decreases dependability on any particular one.

### Potential Solutions

Support the Deepinfra API. See their [docs](https://deepinfra.com/docs/).

**Comment by klieret** [comment]
I agree with this. I'd be open to add litellm, ideally starting with some of the less important or newer models (anything but gpt4, claude 2, claude 3). Basically I'd want to move slowly so we don't disrupt the research that uses those 3 models. Please keep in mind that a lot of the cheaper models are too bad to really be used for swe-agent.

**Comment by ofirpress** [comment]
We're going to support something like LiteLLM which will deprecate the need for this issue. Closing.
