### ISSUE TITLE
Why is GPT-3.5 not functioning while GPT-4 works in the SWE agent?"

### ISSUE THREAD

**Issue by Narender-007** [princeton-nlp/SWE-agent#273]
### Describe the feature

using gpt4 working fine everything happy with the gpt4 but gpt4 have too much cost , then switch to gpt4 to gpt-3.5 turbo 116 didn't get the results from gpt-3.5 what is the reason behind please can you share.

```
2024-04-25 15:24:28,671 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2024-04-25 15:24:28,672 - openai._base_client - INFO - Retrying request to /chat/completions in 10.808000 seconds
2024-04-25 15:24:40,588 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
WARNING  Cost limit exceeded
INFO     💭 THOUGHT (primary)
         Exit due to cost limit
INFO     🎬 ACTION (primary)
         exit_cost
INFO     Saved trajectory to
         trajectories/narender/gpt-3.5-turbo-16k-0613__joaomdmoura__crewAI__default_from_url__t-0.00__p-0.95__c-3.00__install-1/joaomdmoura__crewAI-i5
         11.traj
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@########################## {'exit_status': 'exit_cost', 'model_stats': {'total_cost': 0.1754995, 'instance_cost': 0.1754995, 'tokens_sent': 116205, 'tokens_received': 596, 'api_calls': 9}}
**INFO     Saved predictions to
         trajectories/narender/gpt-3.5-turbo-16k-0613__joaomdmoura__crewAI__default_from_url__t-0.00__p-0.95__c-3.00__install-1/all_preds.jsonl       
INFO     No patch to save.**
```

thanks in advance.

### Potential Solutions

![image](https://github.com/princeton-nlp/SWE-agent/assets/57932042/d7a169db-3942-40b4-80a7-60546043ef66)

**Comment by klieret** [comment]
>  then switch to gpt4 to gpt-3.5 turbo 116 didn't get the results from gpt-3.5 what is the reason behind please can you share.

gpt-3.5 is not as good as gpt4, so it might not converge to a solution and still exceed its cost limit.

**Comment by klieret** [comment]
Can't do much more without more concrete information, but it sounds pretty reasonable that gpt-3.5 fails at doing some things that gpt-4 can do
