### ISSUE TITLE
[feature req] New model for testing: DummyAgent

### ISSUE THREAD

**Issue by ofirpress** [princeton-nlp/SWE-agent#279]
For testing purposes we should have a dummy agent. 

It should just work with @klieret's test issue in the test repo. 

It should just sequentially execute the commands that fix that issue in that repo.

This would be useful for end-to-end testing purposes and would save money on API requests.

I also have some small ideas on how to improve this idea slightly more.

**Comment by ofirpress** [comment]
Kilian I'd love to hear your thoughts. Just wanted to file this before I forget.

**Comment by klieret** [comment]
Isn't that very similar to the replay model though? Where would we get the commands that fix the issue?

If we had `gpt4` solve an issue before, we can take the trajectory and use the replay model to replay everything as if the LM was doing it. 

This is the primary means by which I'm testing swe-agent at the moment :)

**Comment by ofirpress** [comment]
ok let me talk to you about this next time we chat, i think we can make this DummyAgent a bit smarter and therefore it would maybe be better than the replay solution. anyways this is not urgent at all

**Comment by ofirpress** [comment]
ok I talked with Kilian and one of the tests almost does exactly this and at some point we'll update that test to verify environment outputs too
