### ISSUE TITLE
Please create a docker build so that the local conda install is not needed

### ISSUE THREAD

**Issue by NimbleCapricorn** [princeton-nlp/SWE-agent#28]
The whole point of docker is that images can be run as released, without the user having to rebuild it every time. 
If the API keys are the issue, **config files, environmental variables and docker secrets** can be used to circumvent having to bake api keys into the build.

**Comment by cpendery** [comment]
Just calling out that the docker image agent `swe-agent` is orchestrated from the `run.py` script. They wouldn't be able to create a docker image containing everything unless they use something like mounting *docker.sock* or using *dind*.

**Comment by NimbleCapricorn** [comment]
There is already a branch that implements this request, waiting for merging. So no, that is not a blocker issue.
