### ISSUE TITLE
Create SWE-agent github codespace

### ISSUE THREAD

**Issue by JensRoland** [princeton-nlp/SWE-agent#281]
### Describe the feature

Since getting SWE-agent up and running locally can be difficult for newcomers and currently does not seem to work on Apple Silicon Macs, it would be nice to have a documented way to run it in the cloud instead, with a (secured) API endpoint exposed for direct (curl style) or programmatic use.

Since the use case for SWE-agent inherently involves connecting to cloud APIs to run model inference anyway, this seems like a natural mode of operation -- if I am running AWS Bedrock models anyway, why not run the agent orchestrator on ECS/Fargate?

### Potential Solutions

Since SWE-agent is already containerized, this is probably more a matter of adding a How-To to the documentation than actually adding any new features, but it also helps make the deployment more repeatable for users.

**Comment by Josephrp** [comment]
this is smart, on the readme, there could easily be a `deploy to github codespaces` button , or something similar for "our favorite cloud provider" , or even huggingface.

**Comment by ofirpress** [comment]
We would enthusiastically support anything that would make SWE-agent easier for more people to use. Especially if it's just a matter of setting up a guide or an image somewhere.

**Comment by klieret** [comment]
> Since getting SWE-agent up and running locally can be difficult for newcomers and currently does not seem to work on Apple Silicon Macs

@JensRoland Please let us know about the difficulties you run into. It should _absolutely_ works on Apple Silicon Macs. I think our whole team is running on Apple Silicon.

**Comment by Josephrp** [comment]
i dont know what @JensRoland has in mind but "codespaces" could be an easy(ier) place to start , happy to pitch in , but there's folks that set up the development environments that will also know how to do it ;-)

**Comment by klieret** [comment]
I agree that bundling the dependencies and everything in a codespace would be a nice way to help new developers get started :)

**Comment by JensRoland** [comment]
@klieret I switched to an M1 Macbook not too long ago and migrated all of my old data and settings from my old Intel Mac. This seems to have left my Homebrew installation in a less-than-ideal state, including things like Python, Pyenv, Docker, and Colima. So when I first tried running SWE-agent, I got errors related to Colima/Docker and tried reinstalling them. That led me to the fun error:

```sh
brew cleanup Error: Permission denied @ apply2files
```

I was stuck on that for a while, until I found someone online pointing out that Homebrew apparently doesn't migrate cleanly from Intel to Apple Silicon, and recommended deleting Homebrew and reinstalling everything with the appropriate architecture flags, so I spent an evening doing that. And it did get Colima running again, but as it turns out.... Homebrew now installs to `/usr/local/opt/` rather than `/usr/lib` and a lot of things were still pointing to the old locations, so things were breaking in interesting new ways. Trying to run SWE-agent gave this one:

```sh
dyld[99385]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: <E5AE053B-2D1A-3827-96AC-422BC13EF22B> /Users/jensr/.pyenv/versions/3.9.10/bin/python3.9
  Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
```

Again, some Google-fu took me to a recommendation to simply create a symlink from the non-existing location to the location that holds that file, so I did: `bash-3.2# ln -s /opt//homebrew/lib/libintl.8.dylib /usr/local/opt/gettext/lib/libintl.8.dylib`

But now trying to run SWE-agent gives me this error:

```sh
dyld[5598]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: <E5AE053B-2D1A-3827-96AC-422BC13EF22B> /Users/jensr/.pyenv/versions/3.9.10/bin/python3.9
  Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/gettext/0.22.5/lib/libintl.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/gettext/0.22.5/lib/libintl.8.dylib' (no such file), '/opt/homebrew/Cellar/gettext/0.22.5/lib/libintl.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
```

So I'm stuck with `incompatible architecture (have 'arm64', need 'x86_64')` and that's where I gave up since it seemed to tell me the container wants x86_64 and I'm on arm64. And with the note in the README about compatibility issues with Arm architecture, I thought that was the end of it. So I'm very surprised to hear that you guys are running on M series Macs yourselves? How? Did you sacrifice a goat to Bjarne Stroustrup?

**Comment by JensRoland** [comment]
But back to the original topic: Codespaces seems like a great option, which I would actually prefer to running it locally (even if I could get it to work).

**Comment by ofirpress** [comment]
What would it take to get it to work on codespaces?

**Comment by Josephrp** [comment]
> What would it take to get it to work on codespaces?

just an environment.yaml and a smart little deploy pipeline. you can use the same principle for development environments btw.

**Comment by klieret** [comment]
@JensRoland Could you open a new issue for that? (just copy it over)

> And with the note in the README about compatibility issues with Arm architecture, I thought that was the end of it. So I'm very surprised to hear that you guys are running on M series Macs yourselves?

I think the note in the README is about evaluating on instances/issues from certain repositories (which require the installation of certain dependencies), not for running the software in general.

**Comment by ofirpress** [comment]
We welcome contributions that would enable SWE-agent to run on codespaces. We have a release of things we are working on that will probably come out next week, and then this will be one of our primary focus points.

**Comment by JensRoland** [comment]
> We welcome contributions that would enable SWE-agent to run on codespaces. We have a release of things we are working on that will probably come out next week, and then this will be one of our primary focus points.

Speaking of, I was just lurking through commits on the Web UI branch and it disappeared? What gives? :-)

**Comment by klieret** [comment]
I've set up a basic version. After you create it you still have to do the following:

1. Open terminal
2. Change to root `sudo su` (else you can't use docker)
3. `conda activate swe-agent`

And you should be good to go.

Improvements:

* Step 2 should be improved by adding the user to the correct linux group to talk to docker
* Step 3 should be already done as a post-init stop in [`.devcontainer.json`](https://github.com/princeton-nlp/SWE-agent/blob/main/.devcontainer/devcontainer.json)  (not sure why it's not already working)

**Comment by klieret** [comment]
All done. Will add a video/some documentation that automatically opens in the codespace later today :)

**Comment by ofirpress** [comment]
That's so awesome, thank you so much!!! Do you think it would make sense to put the video in the README? that could be cool

**Comment by Josephrp** [comment]
> That's so awesome, thank you so much!!! Do you think it would make sense to put the video in the README? that could be cool

we'll need to make a gif, then host it accordingly, push and update with the static blob address :-)

**Comment by ofirpress** [comment]
Completed with #294
