### ISSUE TITLE
Document setting a cost limit in README

### ISSUE THREAD

**Issue by JensRoland** [princeton-nlp/SWE-agent#290]
### Describe the feature

Having just run SWE-agent for the first time, I found that it hits the cost ceiling on the first GitHub issue and exits. I appreciate the inclusion of a limit and the low default setting, but I would have liked a heads up before running that first command, so I could have increased the limit before running the command. While I can afford the $3, it seems wasteful that I'll have to start over just because I hit a ceiling.

Now, I don't know if the aborted command 'trajectory' is resumable? If it is not, then that run is indeed wasted compute and cost. But if it is resumable, then that would be nice to highlight in the documentation, and possibly in the "exit due to cost limit" commandline output.

Again, thanks for an exciting project. I hope to be able to contribute down the line.

### Potential Solutions

Add a line in the README about setting a cost limit just above the `python run.py` command.

If aborted trajectories are resumable, add a note about it to the CLI output when aborting a trajectory due to cost

**Comment by ofirpress** [comment]
we could just add --cost-limit 2.00 to the command

**Comment by klieret** [comment]
I wouldn't want to make the examples from the readme longer than they already are. 

It's also increasingly unlikely that the agent will solve the issue the more turns you take, so raising the cost limit will only help to some extend.

**Comment by klieret** [comment]
I also think that restarting from a trajectory would needlessly complicate the code without more refactoring.

**Comment by ofirpress** [comment]
Ya no reason to do 'restart from traj' now. I'm fine with not adding the cost-limit to the command
