### ISSUE TITLE
BLOCKLIST ERROR: Git 

### ISSUE THREAD

**Issue by YashRajOjha-Draup** [princeton-nlp/SWE-agent#296]
### Describe the issue

I am using docker to run SWE-agent on my repo using the command below, 

```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \ 
-v $(pwd)/keys.cfg:/app/keys.cfg sweagent/swe-agent-run:latest \
python run.py --image_name=sweagent/swe-agent:latest \
--model_name gpt4 \  
--data_path https://github.com/abc/abc_xyz/issues/1821 \
--repo_path https://github.com/abc/abc_xyz/tree/feature_branch \
--config_file config/default_from_url.yaml
```

The issue described is as follows, , 

## Task
- using git checkout switch to `feature_branch`, 
- locate the `sub folder` in `project folder`, 
- modify the `preprocess_input` function in the inference file to correct Unicode errors and eliminate emojis from the string, while preserving the original casing of the text

This is the error I get, 
```
WARNING  BLOCKLIST ERROR                                                                                                          
Interactive operation 'git' is not supported by this environment 

```

Is there a way to mention feature branch, and get the tasks from the issue solved?

**Comment by klieret** [comment]
Hi @YashRajOjha-Draup . Thank you for your question.

The blocklist is part of the config. You can create a new config file and remove `git` from it there.

It's blocked by default, because we're focused on questions that have a patch file as an answer. Knowing to use `git` is an orthogonal skill to fixing bugs etc.

**Comment by YashRajOjha-Draup** [comment]
How do we create and modify the config file to remove git from blocklist? the examples in the folder config/configs don't explicitly mention a blocklist.

**Comment by klieret** [comment]
You should be able to still specify the `blocklist` key according to the dataclass here: https://github.com/princeton-nlp/SWE-agent/blob/ad582688687146c09d04b49a36a40c517ba9fd66/sweagent/agent/agents.py#L43
