### ISSUE TITLE
No such file of instance.traj, only its parent directory exists.

### ISSUE THREAD

**Issue by mannaandpoem** [princeton-nlp/SWE-agent#3]
## issue
No such file of instance.traj, only its parent directory exists. Could you please provide the specific file of instance.traj for the demonstrations section within the `config/default.yaml` file?

## This is log：
INFO     DEMONSTRATION:
         trajectories/demonstrations/replay__marshmallow-code__marshmallow-1867__default__t-0.20__p-0.95__c-2.00__install-1___install_from_source/marshmallow-code__marshmallow-186
         7.traj
Traceback (most recent call last):
  File "/home/manna/SWE-agent/run.py", line 109, in main
    info = agent.run(
  File "/home/manna/SWE-agent/sweagent/agent/agents.py", line 638, in run
    self.setup(setup_args, init_model_stats)
  File "/home/manna/SWE-agent/sweagent/agent/agents.py", line 218, in setup
    demo_history = json.load(open(demonstration_path, "r"))["history"]
FileNotFoundError: [Errno 2] No such file or directory: 'trajectories/demonstrations/replay__marshmallow-code__marshmallow-1867__default__t-0.20__p-0.95__c-2.00__install-1___install_from_source/marshmallow-code__marshmallow-1867.traj'
WARNING  ❌ Failed on pvlib__pvlib-python-i1603: [Errno 2] No such file or directory:
         'trajectories/demonstrations/replay__marshmallow-code__marshmallow-1867__default__t-0.20__p-0.95__c-2.00__install-1___install_from_source/marshmallow-code__marshmallow-18
         67.traj'
INFO     Beginning environment shutdown...
INFO     Agent container stopped
INFO     🌱 Environment Initialized

**Comment by john-b-yang** [comment]
This should be fixed as of 7221bdcec3e6f161f1a6a1b70ec60de8f826c4cd! The error is being raised because it's looking for a trajectory (to be used as a demonstration for the agent) that doesn't exist. The folder with the necessary paths has been added in the latest commit.

**Comment by joskfg** [comment]
Now it works, thanks!

**Comment by geniusunil** [comment]
I still get this error, am I missing something here?

**Comment by klieret** [comment]
@geniusunil Let's move this discussion to https://github.com/princeton-nlp/SWE-agent/issues/309. Are you running from the docker container as well? Please comment at #309
