### ISSUE TITLE
Have I installed incorrectly if I encounter environment pip installation errors during inference/eval?

### ISSUE THREAD

**Issue by mnskim** [princeton-nlp/SWE-agent#325]
### Describe the issue

Hello, and thank you for an amazing code release of SWE-Agent.

I'm having slight issues during inference/evaluation,
more specifically pip install sometimes failing in inference and evaluation,
 in roughly 10~20% of examples on the dev set of swe-bench lite.

I'm wondering if these are expected or due to my setting up the docker slightly differently (I'm using a docker container built using sweagent/swe-agent-run:latest, but without the --rm flag)

Any help/pointers would be appreciated!

**Comment by klieret** [comment]
Can't do much without a concrete example. However, it seems like you're asking about `pip` installation as involved by the agent while trying to solve the issue?

There's a way of explicitly specifying an environment for the agent to run in, see https://github.com/princeton-nlp/SWE-agent/pull/153 (working on better documenting this feature)

**Comment by mnskim** [comment]
Hi @klieret , thanks so much for the response,
I tried to reproduce the error, and here is one example that I could reproduce just now:
<img width="981" alt="swebench_ex1" src="https://github.com/princeton-nlp/SWE-agent/assets/48931129/f7e669aa-a670-4cd9-af40-ddff2603251d">
 
 In the meanwhile I will try the method suggested in the link!

**Comment by klieret** [comment]
Please send me the full log as text (e.g., upload it as a text file here) and include the exact commands that you've run. I can't really tell what's going on based on the info that you've sent me.

**Comment by mnskim** [comment]
[testlog.log](https://github.com/princeton-nlp/SWE-agent/files/15268554/testlog.log)

Thank you! Here is the full log from the eval, and the exact command was
`./run_eval.sh ../trajectories/root/gpt4__SWE-bench-Lite__default__t-0.00__p-0.95__c-2.00__install-1/all_preds.jsonl`

**Comment by klieret** [comment]
But tl;dr: You've installed swe-agent correctly, so this seems to be more related to the swe-bench setup.

Btw, what's your OS/architecture? Because of this:

![image](https://github.com/princeton-nlp/SWE-agent/assets/13602468/1556758c-03a2-4984-96a2-1ceed4a31aaf)

**Comment by sfc-gh-minkim** [comment]
Thank you for the update, my platform is arm64 - maybe this is part of the issue!

A related question I had was: I'm a bit confused whether the inference step (run.py) is meant to install specific versions of python libraries (i.e. sqlfluff 0.6.9 for sqlfluff__sqlfluff-1625), or is the agent supposed to be able to do pip installs? (It seemed like I was getting some python lib version related errors, but these could be avoided by specifying the exact sqlfluff version, for example)

**Comment by mnskim** [comment]
Thank you for the update, my platform is arm64 - maybe this is part of the issue!

A related question I had was: I'm a bit confused whether the inference step (run.py) is meant to install specific versions of python libraries (i.e. sqlfluff 0.6.9 for sqlfluff__sqlfluff-1625), or is the agent supposed to be able to do pip installs? (It seemed like I was getting some python lib version related errors, but these could be avoided by specifying the exact sqlfluff version, for example)

**Comment by klieret** [comment]
Very good question. If you run over a single issue, you can manually specify them (`--environment_setup`), if you run over swe-bench, it's gonna look up dependencies from the swe-bench package (`swebench/harness/constants.py`)

**Comment by mnskim** [comment]
I appreciate the help & clarification, thanks again!
