### ISSUE TITLE
"Copy patch" button should appear next to patch submission

### ISSUE THREAD

**Issue by klieret** [princeton-nlp/SWE-agent#327]
After the model submits, we see a patch in the Terminal. There should be a copy button ("copy patch") similar to the one shown at the end of the log file so that users can easily copy the patch.

This is the patch:

<img width="761" alt="image" src="https://github.com/princeton-nlp/SWE-agent/assets/13602468/1ec4c0e5-6d06-498a-ad75-1270adf4677c">

This is the copy button at the log file:

<img width="750" alt="image" src="https://github.com/princeton-nlp/SWE-agent/assets/13602468/ecfc25c6-271f-4203-8513-5e6dc3ca3641">

> [!tip] 
> General tips for frontend contributors:
> * Please open a separate PR for every issue that you address. Try to keep PRs small and concise (if you're thinking of bigger refactorings, please let us know)
> * In the web UI under "Extra Settings" there's a switch to run without needing API credits for testing purposes
> * Please install pre-commit (`pip install pre-commit && pre-commit install`) to ensure that your submission follows the styling guidelines

**Comment by Prathamesh010** [comment]
Should the copy button appear for the whole EnvFeed or just the patch where it is not text?

**Comment by klieret** [comment]
Hi! It would've been just for the final patch that's being displayed. But the web UI is also not a priority of this project anymore (we want to focus on the core agent), so let me close this as not planned for the moment.
