### ISSUE TITLE
Auto-scrolling in web-UI should only be active if user hasn't scrolled up.

### ISSUE THREAD

**Issue by klieret** [princeton-nlp/SWE-agent#328]
Every time a new message appears in one of the feeds/logs of the web UI, we scroll to the bottom. However, if a user wants to read a certain part during the run and has scrolled up, we shouldn't scroll down.

> [!tip] 
> General tips for frontend contributors:
> * Please open a separate PR for every issue that you address. Try to keep PRs small and concise (if you're thinking of bigger refactorings, please let us know)
> * In the web UI under "Extra Settings" there's a switch to run without needing API credits for testing purposes
> * Please install pre-commit (`pip install pre-commit && pre-commit install`) to ensure that your submission follows the styling guidelines

**Comment by ofirpress** [comment]
+1

**Comment by ofirpress** [comment]
@klieret we can close this, right?

**Comment by klieret** [comment]
Thanks for the reminder, yes

**Comment by ofirpress** [comment]
ty
