### ISSUE TITLE
Allow to maximize windows of web UI

### ISSUE THREAD

**Issue by klieret** [princeton-nlp/SWE-agent#329]
Similar to https://swe-agent.com/demo, we want to have an expand button on the top right of the three sub-panes that opens a larger popup of the same window.

Here's the code from swe-agent.com/demo (look for `TerminalPanel.js` etc.)
 
[swe-agent-website.tar.gz](https://github.com/princeton-nlp/SWE-agent/files/15268531/swe-agent-website.tar.gz)

> [!tip] 
> General tips for frontend contributors:
> * Please open a separate PR for every issue that you address. Try to keep PRs small and concise (if you're thinking of bigger refactorings, please let us know)
> * In the web UI under "Extra Settings" there's a switch to run without needing API credits for testing purposes
> * Please install pre-commit (`pip install pre-commit && pre-commit install`) to ensure that your submission follows the styling guidelines

**Comment by ofirpress** [comment]
this would be cool
