### ISSUE TITLE
Cannot change "Setup script" (for Environment) in Web UI

### ISSUE THREAD

**Issue by zgrannan** [princeton-nlp/SWE-agent#333]
### Describe the bug

I cannot modify the "Setup script" section in the Envionment tab in the web UI. The screenshot below shows some warnings in the console; the second one is probably relevant.
<img width="1500" alt="image" src="https://github.com/princeton-nlp/SWE-agent/assets/1141948/78ca8b8e-5dcb-4464-925f-b231cc102d59">

### Steps/commands/code to Reproduce

Follow the installation instructions from the README, Launch the web UI via `./start_web_ui.sh` click the "Environment" tab, switch from "Python versions and packages" to "Path to shell script", attempt to change the shell script

### Error message/results

The above screenshot contains the warnings. It's not possible to change the shell script.

### System Information

macOS Sonoma 14.4.1, Python 3.9.6

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran
- [X] I have copied the **full** log file/error message that was the result (if applicable)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
Thanks for the report, you're absolutely right! Gonna fix that in the next ~2h (probalby just some `value=""` that should be a `defaultValue`)

**Comment by klieret** [comment]
In the meantime you can probably do most of setup things by switching the dropdown on the top to "python version and pacakges"
