### ISSUE TITLE
UI improvements for reading trajectories using the new web UI

### ISSUE THREAD

**Issue by ofirpress** [princeton-nlp/SWE-agent#338]
At some point we're gonna make it so you can use the new web UI to view trajectories. I think we could add some UI improvements to make it nicer to read existing trajectories:

1. Make it so when you scroll up/down just the thoughts, it automatically also scrolls the outputs to the right place, and vice versa.
2. Syntax highlighting for output column if we don't have that yet.
3. better indication of which command outputs relate to which thoughts. not sure how this could look, could just be lines from the terminal column bubbles to the thought column bubbles, we might have to think about this. maybe instead, we could do like in the 'old html viewer' where the thoughts and terminal outputs are interleaved, thus making it obvious which terminal outputs are related to which thoughts...
4. open to any other ideas people may have

**Comment by klieret** [comment]
I was thinking of just taking the current UI minus the log file viewer and just immediately populating both feeds. That would solve 1, 2, 3 already. I don't think it is wise to develop a completely different frontend just for viewing trajectories.

**Comment by ofirpress** [comment]
i definitely don't think we should have 2 viewers. 

1 isn't exactly implemented yet- the scrolling only happens when you mouseover.

anyways this isn't urgent, let's discuss next time we sync
