### ISSUE TITLE
simplify readme

### ISSUE THREAD

**Issue by ofirpress** [princeton-nlp/SWE-agent#339]
The readme is wayyyy too complicated right now. 

We need to make it really easy for people who just wanna use it on an issue to use it on one. They don't care about swe-bench evals and ACI and all that stuff. let's make it easy for them. 

then below we can have a section about how to use it with swe-bench and we can provide the deeper dive into what ACI is and all that stuff.

**Comment by klieret** [comment]
I think we should just have a simple sphinx/mkdocs page with some sub-pages

**Comment by ofirpress** [comment]
I think most people don't read those things. Everyone reads the readme

**Comment by klieret** [comment]
It's not gonna fit well on one page one way or another once we expand the documentation. We can just add links from the main readme for the different sections. All bigger projects that I've seen have a dedicated documentation page.

**Comment by ofirpress** [comment]
oh ya for sure. we need to have a short readme, it can link to other stuff for the details

**Comment by ofirpress** [comment]
2 things:
1) i think we should have a working example that gpt-4 easily fixes
2) i think we should put back the ACI text, but at the bottom. i'll discuss with john

**Comment by 1of13** [comment]
I appreciate your hard work on this project. Thank you for the updated documentation. It is now easy to use SWE-Agent on my code.

**Comment by ofirpress** [comment]
Thanks! And yes, thank you @klieret !

**Comment by moresearch** [comment]
Maybe a fixed web link of the benchmark image so that it updates everywhere whenever there is a new agent.
