### ISSUE TITLE
What are the issues that SWE-Agent can resolve?

### ISSUE THREAD

**Issue by ramsey-coding** [princeton-nlp/SWE-agent#349]
### Describe the issue

What are the issues that SWE-Agent can resolve? I cannot find the list of issues that SWE-Agent can resolve in the repository.

### Suggest an improvement to documentation

Please make the evaluation section better.

**Comment by klieret** [comment]
See https://github.com/swe-bench/experiments/blob/main/evaluation/test/20240402_sweagent_gpt4/results/results.json and similar folders
