### ISSUE TITLE
Why have you implemented SWE-Agent from scratch instead of using existing frameworks like AutoGPT or Baby AGI?

### ISSUE THREAD

**Issue by ramsey-coding** [princeton-nlp/SWE-agent#366]
### Describe the issue

I noticed that the SWE-Agent has been implemented from scratch. There are several existing frameworks, such as AutoGPT and Baby AGI, that provide robust functionality for creating LLM-based agents. These frameworks could potentially save development time and leverage existing solutions for common challenges.

Could you please provide more details on the rationale behind the decision to develop SW-Agent from scratch? Specifically, I am curious to know:

- What specific requirements or goals led you to choose a custom implementation over existing frameworks?
- Were there any limitations or shortcomings in AutoGPT or Baby AGI that influenced this decision?
- How does the custom implementation of SW-Agent compare to these frameworks in terms of performance, scalability, and maintainability?
Are there any plans to integrate features from these frameworks in the future?

Understanding these points would be really helpful in appreciating the design choices and the potential advantages of the custom implementation.

Thank you!

**Comment by ofirpress** [comment]
We think SWE-bench is a pretty good way to compare different agent systems. If any of those systems get good numbers on SWE-bench we will consider switching over to those frameworks.

**Comment by ramsey-coding** [comment]
@ofirpress that was not the question. The question is why you chose to implement from scratch?
