### ISSUE TITLE
How to implement the swe agent on local issues and local repo path inside local machine?

### ISSUE THREAD

**Issue by MAhmadUzair** [princeton-nlp/SWE-agent#376]
### Describe the issue

I want to know which command will be used to operate the swe agent on the local repo inside the local machine. Also how to give the data_path repo_path to agent? The  sample I got is below but do not know how to give data path and repo path from local machine

python3.9 run.py --model_name gpt4 --data_path  " " --repo_path " "   --config_file config/default.yaml --per_instance_cost_limit 2.00 --apply_patch_locally

**Comment by klieret** [comment]
Sorry, I'm a bit confused to by the question. Does this not work? 

```bash
python3.9 run.py --model_name gpt4 --data_path /path/to/a/textfile.md --repo_path /path/to/your/repo --config_file config/default.yaml --per_instance_cost_limit 2.00 --apply_patch_locally
```

**Comment by klieret** [comment]
Just to double check, you're using the local installation of swe-agent, right? (for the docker one, you'd have to make sure to mount things into the container first and then point to the mount points -- but we don't really recommend using the all-in-docker installation anymore because it's just easier to install swe-agent properly)

**Comment by MAhmadUzair** [comment]
No, I am confused in giving the data_path and repo_path in this command.
Let's say I have a repo(project) in Local disk D space and I want to
resolve the issue inside of it. How can I give the path in this command?
That I want to ask.

**Comment by MAhmadUzair** [comment]
I have cloned your repo and put the keys inside it and just ran the
setup.sh. Now, the Question is! I want to resolve the issue of the project
which is not on Git Hub, it is located on my local machine. So in this way,
I want to resolve the local issue in the local repo. But I am stuck between
giving the data_path and repo_path.

**Comment by klieret** [comment]
You simply give it the paths on your local machine. It doesn't have to be on github. `data_path` needs to point to a text file containing the issue, `repo_path` needs to be the path to your directory with the code.

**Comment by MAhmadUzair** [comment]
Can you put any video link how to do that?
