### ISSUE TITLE
Local Implementation of SWE agent does not work inside local Machine! (Local issue & Local repo)

### ISSUE THREAD

**Issue by MAhmadUzair** [princeton-nlp/SWE-agent#385]
### Describe the bug

I am trying to resolve the issue of my project on my local machine. This is what I have done.

I cloned the SWE agent repo and put the keys.cfg and just hit ./setup.sh to run it (docker successfully ran). 

After that, I pasted this command to run: 

```
python3.9 run.py --model_name gpt4 --data_path "\\wsl.localhost\Ubuntu-20.04\home\uzair\swe-agent\data_path" --repo_path "\\wsl.localhost\Ubuntu-20.04\home\uzair\swe-agent\repo_path" --config_file config/default.yaml --per_instance_cost_limit 2.00 --apply_patch_locally
```

Whereas, datapath = \\wsl.localhost\Ubuntu-20.04\home\uzair\swe-agent\data_path (This is my directory, there I have txt file named issue, inside this text file I asked issue to resolve).

Repo_path = \\wsl.localhost\Ubuntu-20.04\home\uzair\swe-agent\repo_path   (This directory contains the test.py file which has issues on it.)

The problem is when I try to paste this command > 

```
python3.9 run.py --model_name gpt4 --data_path "\\wsl.localhost\Ubuntu-20.04\home\uzair\swe-agent\data_path" --repo_path "\\wsl.localhost\Ubuntu-20.04\home\uzair\swe-agent\repo_path" --config_file config/default.yaml --per_instance_cost_limit 2.00 --apply_patch_locally
```

It shows some errors. Attached for you to look at this. I am not sure where I am mistaken or if your repo has issues. Am I giving paths correctly?
![issue](https://github.com/princeton-nlp/SWE-agent/assets/100315421/de9f37ce-31b6-495b-9370-8814dab05ea0)

### Steps/commands/code to Reproduce

python3.9 run.py --model_name gpt4 --data_path "\\wsl.localhost\Ubuntu-20.04\home\uzair\swe-agent\data_path" --repo_path "\\wsl.localhost\Ubuntu-20.04\home\uzair\swe-agent\repo_path" --config_file config/default.yaml --per_instance_cost_limit 2.00 --apply_patch_locally

### Error message/results

![issue](https://github.com/princeton-nlp/SWE-agent/assets/100315421/167769a0-5b49-49a8-9516-b43ad72064e0)

### System Information

I am using windows base subsystem Linux having core i7 8 gen, 16 gbs ram. 

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran
- [X] I have copied the **full** log file/error message that was the result (if applicable)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
The error message here is unfortunately very unclear, because `data_path` can handle a lot of different inputs. 

But your mistake is probably that you point `data_path` at a directory, rather than a text file with a problem statement. 

Our [new documentation](https://princeton-nlp.github.io/SWE-agent/usage/cl_tutorial/) now has a concrete example for using local repos/files that you can try.

**Comment by klieret** [comment]
Btw, **please** don't put screenshots of error messages, just copy them as text!
