### ISSUE TITLE
Bug during setup

### ISSUE THREAD

**Issue by albertotn** [princeton-nlp/SWE-agent#386]
### Describe the bug

During setup.sh running I receive an error message

### Steps/commands/code to Reproduce

on windows, git bash:
1. clone repository
2. pip install --editable .
3. ./setup.sh

### Error message/results

```#13 [ 9/14] COPY docker/getconda.sh .
#13 CACHED

#14 [10/14] RUN bash getconda.sh x86_64     && rm getconda.sh     && mkdir /...
#14 0.296 getconda.sh: line 2: $'\r': command not found
#14 0.297 getconda.sh: line 6: $'\r': command not found
#14 0.297 getconda.sh: line 12: syntax error near unexpected token `elif'
'14 0.297 getconda.sh: line 12: `elif [[ "$arch" == "aarch64" || "$arch" == "arm64" ]]; then
#14 0.297 arch, x86_64
#14 ERROR: executor failed running [/bin/sh -c bash getconda.sh ${TARGETARCH}     && rm getconda.sh     && mkdir /root/.conda     && bash miniconda.sh -b     && rm -f miniconda.sh]: exit code: 2
------
 > [10/14] RUN bash getconda.sh x86_64     && rm getconda.sh     && mkdir /root/.conda     && bash miniconda.sh -b     && rm -f miniconda.sh:
------
executor failed running [/bin/sh -c bash getconda.sh ${TARGETARCH}     && rm getconda.sh     && mkdir /root/.conda     && bash miniconda.sh -b     && rm -f miniconda.sh]: exit code: 2
```

### System Information

Windows 10 x64
python 3.12.3

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran
- [X] I have copied the **full** log file/error message that was the result (if applicable)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
Hi @albertotn , thanks for reporting this.

This sounds like what was reported in https://github.com/princeton-nlp/SWE-agent/issues/42. 

In particular, @cpendery had the suggestion that this might have to do with issues during cloning: https://github.com/princeton-nlp/SWE-agent/issues/42#issuecomment-2038052227

Generally though, you can currently only run SWE-agent on WSL, not on normal Windows (@cpendery also had some fixes for that, but so far there were always some issues that took priorities over them, so unfortunately this might still take a few weeks to be done).

**Comment by albertotn** [comment]
thanks @klieret I've tried the solution in #42  and get the same problem:

```
#13 [ 9/14] COPY docker/getconda.sh .
#13 CACHED

#14 [10/14] RUN bash getconda.sh x86_64     && rm getconda.sh     && mkdir /...
#14 0.297 getconda.sh: line 2: $'\r': command not found
#14 0.297 getconda.sh: line 6: $'\r': command not found
#14 0.297 arch, x86_64
#14 0.297 getconda.sh: line 12: syntax error near unexpected token `elif'
'14 0.297 getconda.sh: line 12: `elif [[ "$arch" == "aarch64" || "$arch" == "arm64" ]]; then
#14 ERROR: executor failed running [/bin/sh -c bash getconda.sh ${TARGETARCH}     && rm getconda.sh     && mkdir /root/.conda     && bash miniconda.sh -b     && rm -f miniconda.sh]: exit code: 2
------
 > [10/14] RUN bash getconda.sh x86_64     && rm getconda.sh     && mkdir /root/.conda     && bash miniconda.sh -b     && rm -f miniconda.sh:
------
executor failed running [/bin/sh -c bash getconda.sh ${TARGETARCH}     && rm getconda.sh     && mkdir /root/.conda     && bash miniconda.sh -b     && rm -f miniconda.sh]: exit code: 2
```

**Comment by klieret** [comment]
An alternative option would be to just do `docker pull sweagent/swe-agent:latest` (`setup.sh` builds the same image, only locally)

**Comment by klieret** [comment]
But there's probably something wrong with your setup/cloning if you get this, you should look into tools that investigate the line endings and find out why you have windows-style line endings.
