### ISSUE TITLE
pip error: editable mode currently requires a setup.py based build

### ISSUE THREAD

**Issue by MAhmadUzair** [princeton-nlp/SWE-agent#398]
### Describe the bug

I am trying to open the Web UI. But It is showing some errors.

Here is What I have done.

1. Cloned the repo in my Ubuntu terminal
2. Create a virtual environment.
3. Installed all dependencies.

```
(myenv) uzair@UZAIR:~/project/SWE-agent$ pip install -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/uzair/project/SWE-agent
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
(myenv) uzair@UZAIR:~/project/SWE-agent$ ./start_web_ui.sh

up to date, audited 1819 packages in 4s

349 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (2 moderate, 6 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[PM2] Starting /home/uzair/.nvm/versions/node/v20.13.1/bin/npm in fork_mode (1 instance)
[PM2] Done.
┌────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ swe-agent    │ default     │ 0.39.3  │ fork    │ 98895    │ 0s     │ 0    │ online    │ 0%       │ 19.3mb   │ uzair    │ disabled │
└────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2][WARN] Current process list is not synchronized with saved list. Type 'pm2 save' to synchronize.
* If you are running on your own machine, then a browser window
  should have already opened. If not, wait a few more seconds, then
  open your browser at http://localhost:3000
* If you are running in github codespaces, please click the popup
  that offers to forward port 3000 (not 8000!).
  Missed it? Find more information at
  https://princeton-nlp.github.io/SWE-agent/installation/codespaces#running-the-web-ui
* Something went wrong? Please check
  web_api.log for error messages!
  ```
```
 (myenv) uzair@UZAIR:~/project/SWE-agent$ ls
CHANGELOG.md  README.md    build_deploy.sh  docker           evaluation  make_demos       myenv              pyproject.toml        run.py         setup.sh         tests
Dockerfile    __pycache__  codecov.yml      docs             inspector   mkdocs.yml       package-lock.json  release_dockerhub.sh  run_replay.py  start_web_ui.sh  trajectories
LICENSE       assets       config           environment.yml  keys.cfg    mlc_config.json  package.json       requirements.txt      scripts        sweagent         web_api.log
```

### Steps/commands/code to Reproduce

```
(myenv) uzair@UZAIR:~/project/SWE-agent$ pip install -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/uzair/project/SWE-agent
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
(myenv) uzair@UZAIR:~/project/SWE-agent$ ./start_web_ui.sh

up to date, audited 1819 packages in 4s

349 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (2 moderate, 6 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[PM2] Starting /home/uzair/.nvm/versions/node/v20.13.1/bin/npm in fork_mode (1 instance)
[PM2] Done.
┌────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ swe-agent    │ default     │ 0.39.3  │ fork    │ 98895    │ 0s     │ 0    │ online    │ 0%       │ 19.3mb   │ uzair    │ disabled │
└────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2][WARN] Current process list is not synchronized with saved list. Type 'pm2 save' to synchronize.
* If you are running on your own machine, then a browser window
  should have already opened. If not, wait a few more seconds, then
  open your browser at http://localhost:3000
* If you are running in github codespaces, please click the popup
  that offers to forward port 3000 (not 8000!).
  Missed it? Find more information at
  https://princeton-nlp.github.io/SWE-agent/installation/codespaces#running-the-web-ui
* Something went wrong? Please check
  web_api.log for error messages!

### Error message/results

(myenv) uzair@UZAIR:~/project/SWE-agent$ pip install -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/uzair/project/SWE-agent
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
(myenv) uzair@UZAIR:~/project/SWE-agent$ ./start_web_ui.sh

up to date, audited 1819 packages in 4s

349 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (2 moderate, 6 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[PM2] Starting /home/uzair/.nvm/versions/node/v20.13.1/bin/npm in fork_mode (1 instance)
[PM2] Done.
┌────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ swe-agent    │ default     │ 0.39.3  │ fork    │ 98895    │ 0s     │ 0    │ online    │ 0%       │ 19.3mb   │ uzair    │ disabled │
└────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2][WARN] Current process list is not synchronized with saved list. Type 'pm2 save' to synchronize.
* If you are running on your own machine, then a browser window
  should have already opened. If not, wait a few more seconds, then
  open your browser at http://localhost:3000
* If you are running in github codespaces, please click the popup
  that offers to forward port 3000 (not 8000!).
  Missed it? Find more information at
  https://princeton-nlp.github.io/SWE-agent/installation/codespaces#running-the-web-ui
* Something went wrong? Please check
  web_api.log for error messages!
```
### System Information

windows

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by constantOut** [comment]
Did you check web_api.log ?
I have same issue and it shows:
Traceback (most recent call last):
  File "$path/SWE-agent-0.4.0/sweagent/api/server.py", line 21, in <module>
    from sweagent import CONFIG_DIR, PACKAGE_DIR
ModuleNotFoundError: No module named 'sweagent'

**Comment by MAhmadUzair** [comment]
> Did you check web_api.log ? I have same issue and it shows: Traceback (most recent call last): File "$path/SWE-agent-0.4.0/sweagent/api/server.py", line 21, in from sweagent import CONFIG_DIR, PACKAGE_DIR ModuleNotFoundError: No module named 'sweagent'

Yes, I am having same issue like above

**Comment by constantOut** [comment]
It works in code spaces https://princeton-nlp.github.io/SWE-agent/installation/codespaces/
But I would like to run all of this locally

**Comment by MAhmadUzair** [comment]
Yes, Man, I tried it yesterday in GitHub codespaces. It wasn't working locally so that's why I raised the issue. Let's wait for the reply.

**Comment by klieret** [comment]
@constantOut you seem to not have successfully installed the package. Please follow [these instructions](https://princeton-nlp.github.io/SWE-agent/installation/source/). Let me know if they do not work. 

@MAhmadUzair I see that there is actually an error during running `pip install -e . `. I think this might be because of an old version of pip. Can you run 

```bash
python3 -m pip install --upgrade pip
```

And then try again? (this is following [this advice](https://stackoverflow.com/questions/69711606/))

**Comment by MAhmadUzair** [comment]
> @constantOut you seem to not have successfully installed the package. Please follow [these instructions](https://princeton-nlp.github.io/SWE-agent/installation/source/). Let me know if they do not work, but do provide full errors and log outputs.
> 
> @MAhmadUzair I see that there is actually an error during running `pip install -e . `. I think this might be because of an old version of pip. Can you run
> 
> ```shell
> python3 -m pip install --upgrade pip
> ```
> 
> And then try again? (this is following [this advice](https://stackoverflow.com/questions/69711606/))

Using `pip install -e . ` I installed the sweagent and also upgraded the pip.


Now ran this command "./start_web_ui.sh".

I got this Read carefully

(myenv) uzair@UZAIR:~/project/SWE-agent$ python3.9 -m pip install --upgrade pip
Collecting pip
  Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-24.0
(myenv) uzair@UZAIR:~/project/SWE-agent$ pip install -e .
Obtaining file:///home/uzair/project/SWE-agent
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: anthropic[bedrock] in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (0.26.1)
Requirement already satisfied: config in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (0.5.1)
Requirement already satisfied: datasets in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (2.19.1)
Requirement already satisfied: docker in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (7.0.0)
Requirement already satisfied: gymnasium in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (0.29.1)
Requirement already satisfied: numpy in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (1.26.4)
Requirement already satisfied: openai>=1.0 in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (1.30.1)
Requirement already satisfied: pandas in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (2.2.2)
Requirement already satisfied: rich in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (13.7.1)
Requirement already satisfied: ruamel.yaml in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (0.18.6)
Requirement already satisfied: swebench>=1.0.1 in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (1.1.5)
Requirement already satisfied: tenacity in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (8.3.0)
Requirement already satisfied: unidiff in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (0.7.5)
Requirement already satisfied: simple-parsing in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (0.1.5)
Requirement already satisfied: together>=1.1.0 in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (1.2.0)
Requirement already satisfied: ollama in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (0.2.0)
Requirement already satisfied: rich-argparse in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (1.4.0)
Requirement already satisfied: flask in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (3.0.3)
Requirement already satisfied: flask-cors in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (4.0.1)
Requirement already satisfied: flask-socketio in ./myenv/lib/python3.9/site-packages (from sweagent==0.2.0) (5.3.6)
Requirement already satisfied: anyio<5,>=3.5.0 in ./myenv/lib/python3.9/site-packages (from openai>=1.0->sweagent==0.2.0) (4.3.0)
Requirement already satisfied: distro<2,>=1.7.0 in ./myenv/lib/python3.9/site-packages (from openai>=1.0->sweagent==0.2.0) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./myenv/lib/python3.9/site-packages (from openai>=1.0->sweagent==0.2.0) (0.27.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in ./myenv/lib/python3.9/site-packages (from openai>=1.0->sweagent==0.2.0) (2.7.1)
Requirement already satisfied: sniffio in ./myenv/lib/python3.9/site-packages (from openai>=1.0->sweagent==0.2.0) (1.3.1)
Requirement already satisfied: tqdm>4 in ./myenv/lib/python3.9/site-packages (from openai>=1.0->sweagent==0.2.0) (4.66.4)
Requirement already satisfied: typing-extensions<5,>=4.7 in ./myenv/lib/python3.9/site-packages (from openai>=1.0->sweagent==0.2.0) (4.11.0)
Requirement already satisfied: beautifulsoup4 in ./myenv/lib/python3.9/site-packages (from swebench>=1.0.1->sweagent==0.2.0) (4.12.3)
Requirement already satisfied: chardet in ./myenv/lib/python3.9/site-packages (from swebench>=1.0.1->sweagent==0.2.0) (5.2.0)
Requirement already satisfied: ghapi in ./myenv/lib/python3.9/site-packages (from swebench>=1.0.1->sweagent==0.2.0) (1.0.5)
Requirement already satisfied: GitPython in ./myenv/lib/python3.9/site-packages (from swebench>=1.0.1->sweagent==0.2.0) (3.1.43)
Requirement already satisfied: python-dotenv in ./myenv/lib/python3.9/site-packages (from swebench>=1.0.1->sweagent==0.2.0) (1.0.1)
Requirement already satisfied: requests in ./myenv/lib/python3.9/site-packages (from swebench>=1.0.1->sweagent==0.2.0) (2.32.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.9.3 in ./myenv/lib/python3.9/site-packages (from together>=1.1.0->sweagent==0.2.0) (3.9.5)
Requirement already satisfied: click<9.0.0,>=8.1.7 in ./myenv/lib/python3.9/site-packages (from together>=1.1.0->sweagent==0.2.0) (8.1.7)
Requirement already satisfied: eval-type-backport<0.3.0,>=0.1.3 in ./myenv/lib/python3.9/site-packages (from together>=1.1.0->sweagent==0.2.0) (0.2.0)
Requirement already satisfied: filelock<4.0.0,>=3.13.1 in ./myenv/lib/python3.9/site-packages (from together>=1.1.0->sweagent==0.2.0) (3.14.0)
Requirement already satisfied: pillow<11.0.0,>=10.3.0 in ./myenv/lib/python3.9/site-packages (from together>=1.1.0->sweagent==0.2.0) (10.3.0)
Requirement already satisfied: pyarrow>=10.0.1 in ./myenv/lib/python3.9/site-packages (from together>=1.1.0->sweagent==0.2.0) (16.1.0)
Requirement already satisfied: tabulate<0.10.0,>=0.9.0 in ./myenv/lib/python3.9/site-packages (from together>=1.1.0->sweagent==0.2.0) (0.9.0)
Requirement already satisfied: typer<0.13,>=0.9 in ./myenv/lib/python3.9/site-packages (from together>=1.1.0->sweagent==0.2.0) (0.12.3)
Requirement already satisfied: jiter<1,>=0.1.0 in ./myenv/lib/python3.9/site-packages (from anthropic[bedrock]->sweagent==0.2.0) (0.4.0)
Requirement already satisfied: tokenizers>=0.13.0 in ./myenv/lib/python3.9/site-packages (from anthropic[bedrock]->sweagent==0.2.0) (0.19.1)
Requirement already satisfied: boto3>=1.28.57 in ./myenv/lib/python3.9/site-packages (from anthropic[bedrock]->sweagent==0.2.0) (1.34.111)
Requirement already satisfied: botocore>=1.31.57 in ./myenv/lib/python3.9/site-packages (from anthropic[bedrock]->sweagent==0.2.0) (1.34.111)
Requirement already satisfied: pyarrow-hotfix in ./myenv/lib/python3.9/site-packages (from datasets->sweagent==0.2.0) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in ./myenv/lib/python3.9/site-packages (from datasets->sweagent==0.2.0) (0.3.8)
Requirement already satisfied: xxhash in ./myenv/lib/python3.9/site-packages (from datasets->sweagent==0.2.0) (3.4.1)
Requirement already satisfied: multiprocess in ./myenv/lib/python3.9/site-packages (from datasets->sweagent==0.2.0) (0.70.16)
Requirement already satisfied: fsspec<=2024.3.1,>=2023.1.0 in ./myenv/lib/python3.9/site-packages (from fsspec[http]<=2024.3.1,>=2023.1.0->datasets->sweagent==0.2.0) (2024.3.1)
Requirement already satisfied: huggingface-hub>=0.21.2 in ./myenv/lib/python3.9/site-packages (from datasets->sweagent==0.2.0) (0.23.1)
Requirement already satisfied: packaging in ./myenv/lib/python3.9/site-packages (from datasets->sweagent==0.2.0) (24.0)
Requirement already satisfied: pyyaml>=5.1 in ./myenv/lib/python3.9/site-packages (from datasets->sweagent==0.2.0) (6.0.1)
Requirement already satisfied: urllib3>=1.26.0 in ./myenv/lib/python3.9/site-packages (from docker->sweagent==0.2.0) (2.2.1)
Requirement already satisfied: Werkzeug>=3.0.0 in ./myenv/lib/python3.9/site-packages (from flask->sweagent==0.2.0) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.2 in ./myenv/lib/python3.9/site-packages (from flask->sweagent==0.2.0) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in ./myenv/lib/python3.9/site-packages (from flask->sweagent==0.2.0) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in ./myenv/lib/python3.9/site-packages (from flask->sweagent==0.2.0) (1.8.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in ./myenv/lib/python3.9/site-packages (from flask->sweagent==0.2.0) (7.1.0)
Requirement already satisfied: python-socketio>=5.0.2 in ./myenv/lib/python3.9/site-packages (from flask-socketio->sweagent==0.2.0) (5.11.2)
Requirement already satisfied: cloudpickle>=1.2.0 in ./myenv/lib/python3.9/site-packages (from gymnasium->sweagent==0.2.0) (3.0.0)
Requirement already satisfied: farama-notifications>=0.0.1 in ./myenv/lib/python3.9/site-packages (from gymnasium->sweagent==0.2.0) (0.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./myenv/lib/python3.9/site-packages (from pandas->sweagent==0.2.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./myenv/lib/python3.9/site-packages (from pandas->sweagent==0.2.0) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in ./myenv/lib/python3.9/site-packages (from pandas->sweagent==0.2.0) (2024.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./myenv/lib/python3.9/site-packages (from rich->sweagent==0.2.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./myenv/lib/python3.9/site-packages (from rich->sweagent==0.2.0) (2.18.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in ./myenv/lib/python3.9/site-packages (from ruamel.yaml->sweagent==0.2.0) (0.2.8)
Requirement already satisfied: docstring-parser~=0.15 in ./myenv/lib/python3.9/site-packages (from simple-parsing->sweagent==0.2.0) (0.16)
Requirement already satisfied: aiosignal>=1.1.2 in ./myenv/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.9.3->together>=1.1.0->sweagent==0.2.0) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in ./myenv/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.9.3->together>=1.1.0->sweagent==0.2.0) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./myenv/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.9.3->together>=1.1.0->sweagent==0.2.0) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in ./myenv/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.9.3->together>=1.1.0->sweagent==0.2.0) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in ./myenv/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.9.3->together>=1.1.0->sweagent==0.2.0) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in ./myenv/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.9.3->together>=1.1.0->sweagent==0.2.0) (4.0.3)
Requirement already satisfied: idna>=2.8 in ./myenv/lib/python3.9/site-packages (from anyio<5,>=3.5.0->openai>=1.0->sweagent==0.2.0) (3.7)
Requirement already satisfied: exceptiongroup>=1.0.2 in ./myenv/lib/python3.9/site-packages (from anyio<5,>=3.5.0->openai>=1.0->sweagent==0.2.0) (1.2.1)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in ./myenv/lib/python3.9/site-packages (from boto3>=1.28.57->anthropic[bedrock]->sweagent==0.2.0) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in ./myenv/lib/python3.9/site-packages (from boto3>=1.28.57->anthropic[bedrock]->sweagent==0.2.0) (0.10.1)
Collecting urllib3>=1.26.0 (from docker->sweagent==0.2.0)
  Using cached urllib3-1.26.18-py2.py3-none-any.whl.metadata (48 kB)
Requirement already satisfied: certifi in ./myenv/lib/python3.9/site-packages (from httpx<1,>=0.23.0->openai>=1.0->sweagent==0.2.0) (2024.2.2)
Requirement already satisfied: httpcore==1.* in ./myenv/lib/python3.9/site-packages (from httpx<1,>=0.23.0->openai>=1.0->sweagent==0.2.0) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in ./myenv/lib/python3.9/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>=1.0->sweagent==0.2.0) (0.14.0)
Requirement already satisfied: zipp>=0.5 in ./myenv/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->flask->sweagent==0.2.0) (3.18.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./myenv/lib/python3.9/site-packages (from Jinja2>=3.1.2->flask->sweagent==0.2.0) (2.1.5)
Requirement already satisfied: mdurl~=0.1 in ./myenv/lib/python3.9/site-packages (from markdown-it-py>=2.2.0->rich->sweagent==0.2.0) (0.1.2)
Requirement already satisfied: annotated-types>=0.4.0 in ./myenv/lib/python3.9/site-packages (from pydantic<3,>=1.9.0->openai>=1.0->sweagent==0.2.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.18.2 in ./myenv/lib/python3.9/site-packages (from pydantic<3,>=1.9.0->openai>=1.0->sweagent==0.2.0) (2.18.2)
Requirement already satisfied: six>=1.5 in ./myenv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->sweagent==0.2.0) (1.16.0)
Requirement already satisfied: bidict>=0.21.0 in ./myenv/lib/python3.9/site-packages (from python-socketio>=5.0.2->flask-socketio->sweagent==0.2.0) (0.23.1)
Requirement already satisfied: python-engineio>=4.8.0 in ./myenv/lib/python3.9/site-packages (from python-socketio>=5.0.2->flask-socketio->sweagent==0.2.0) (4.9.1)
Requirement already satisfied: charset-normalizer<4,>=2 in ./myenv/lib/python3.9/site-packages (from requests->swebench>=1.0.1->sweagent==0.2.0) (3.3.2)
Requirement already satisfied: shellingham>=1.3.0 in ./myenv/lib/python3.9/site-packages (from typer<0.13,>=0.9->together>=1.1.0->sweagent==0.2.0) (1.5.4)
Requirement already satisfied: soupsieve>1.2 in ./myenv/lib/python3.9/site-packages (from beautifulsoup4->swebench>=1.0.1->sweagent==0.2.0) (2.5)
Requirement already satisfied: pip in ./myenv/lib/python3.9/site-packages (from ghapi->swebench>=1.0.1->sweagent==0.2.0) (24.0)
Requirement already satisfied: fastcore>=1.5.4 in ./myenv/lib/python3.9/site-packages (from ghapi->swebench>=1.0.1->sweagent==0.2.0) (1.5.38)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./myenv/lib/python3.9/site-packages (from GitPython->swebench>=1.0.1->sweagent==0.2.0) (4.0.11)
Requirement already satisfied: smmap<6,>=3.0.1 in ./myenv/lib/python3.9/site-packages (from gitdb<5,>=4.0.1->GitPython->swebench>=1.0.1->sweagent==0.2.0) (5.0.1)
Requirement already satisfied: simple-websocket>=0.10.0 in ./myenv/lib/python3.9/site-packages (from python-engineio>=4.8.0->python-socketio>=5.0.2->flask-socketio->sweagent==0.2.0) (1.0.0)
Requirement already satisfied: wsproto in ./myenv/lib/python3.9/site-packages (from simple-websocket>=0.10.0->python-engineio>=4.8.0->python-socketio>=5.0.2->flask-socketio->sweagent==0.2.0) (1.2.0)
Using cached urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
Building wheels for collected packages: sweagent
  Building editable for sweagent (pyproject.toml) ... done
  Created wheel for sweagent: filename=sweagent-0.2.0-0.editable-py3-none-any.whl size=6332 sha256=da9c6b452e2638d5eb23d6d2cf5f92074a093e7860a46680b815c78d17207829
  Stored in directory: /tmp/pip-ephem-wheel-cache-suouo1jd/wheels/4f/09/47/93bd610fef557d497fe7bce9658d1c522a65b4d29757ff0f60
Successfully built sweagent
Installing collected packages: urllib3, sweagent
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.1
    Uninstalling urllib3-2.2.1:
      Successfully uninstalled urllib3-2.2.1
Successfully installed sweagent-0.2.0 urllib3-1.26.18
(myenv) uzair@UZAIR:~/project/SWE-agent$ ./start_web_ui.sh

up to date, audited 1819 packages in 6s

349 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (2 moderate, 6 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[PM2] Starting /home/uzair/.nvm/versions/node/v20.13.1/bin/npm in fork_mode (1 instance)
[PM2] Done.
┌────┬──────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name         │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼──────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ swe-agent    │ default     │ 0.39.3  │ fork    │ 0        │ 0      │ 15   │ errored   │ 0%       │ 0b       │ uzair    │ disabled │
│ 1  │ swe-agent    │ default     │ 0.39.3  │ fork    │ 0        │ 0      │ 15   │ errored   │ 0%       │ 0b       │ uzair    │ disabled │
│ 2  │ swe-agent    │ default     │ 0.39.3  │ fork    │ 46759    │ 0s     │ 0    │ online    │ 0%       │ 22.9mb   │ uzair    │ disabled │
└────┴──────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2][WARN] Current process list is not synchronized with saved list. Type 'pm2 save' to synchronize.
* If you are running on your own machine, then a browser window
  should have already opened. If not, wait a few more seconds, then
  open your browser at http://localhost:3000
* If you are running in github codespaces, please click the popup
  that offers to forward port 3000 (not 8000!).
  Missed it? Find more information at
  https://princeton-nlp.github.io/SWE-agent/installation/codespaces#running-the-web-ui
* Something went wrong? Please check
  web_api.log for error messages!
[PM2] Applying action deleteProcessId on app [swe-agent](ids: [ 0, 1, 2 ])
[PM2] [swe-agent](0) ✓
[PM2] [swe-agent](1) ✓
[PM2] [swe-agent](2) ✓
┌────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
└────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
(myenv) uzair@UZAIR:~/project/SWE-agent$ cat web_api.log
 * Serving Flask app 'server'
 * Debug mode: on
2024-05-23 20:07:46,832 - werkzeug - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8000
2024-05-23 20:07:46,832 - werkzeug - INFO - Press CTRL+C to quit
2024-05-23 20:07:46,832 - werkzeug - INFO -  * Restarting with stat
2024-05-23 20:07:48,734 - werkzeug - WARNING -  * Debugger is active!
2024-05-23 20:07:48,735 - werkzeug - INFO -  * Debugger PIN: 721-064-487

**Comment by klieret** [comment]
Sounds like everything is working correctly. (btw, please format your markdown code blocks, it's hard to read them like this)

**Comment by MAhmadUzair** [comment]
But Whn I open the localhost:3000. 

Web UI does not appear/open.

> Sounds like everything is working correctly. (btw, please format your markdown code blocks, it's hard to read them like this)

**Comment by klieret** [comment]
I've added a more manual way of starting the web server [to the docs](https://princeton-nlp.github.io/SWE-agent/usage/web_ui/), perhaps you can use that to debug and collect more information about what might go wrong.
