### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by joskfg** [princeton-nlp/SWE-agent#4]
Currently after executing the setup.sh I've tried to execute the usage part but it failed because a lot of dependencies were missing. I installed all of them and it worked,  but I don't know why that manual step, maybe I failed something in the setup.

By the other hand, with the [latest commit](7221bdcec3e6f161f1a6a1b70ec60de8f826c4cd), now it works, but it finish without creating the PR, how should it be executed to be able to create the PR?

Great job!

**Comment by john-b-yang** [comment]
Thanks for using our repository and the kind words 😄

For the first question, did you run through the [setup](https://github.com/princeton-nlp/SWE-agent?tab=readme-ov-file#-setup-) steps before following the usage section? If so, happy to take a look at the error message if you still have it.

For the second question, it's possible that SWE-agent does not end up generating a PR/patch when a trajectory terminates if it did not make a successful edit at any turn. This is equivalent to "no answer", which is a valid outcome.

**Comment by joskfg** [comment]
Yes I did the setup steps and after that in the same directory that executed the setup I executed the run.py command and it started failing telling me that I don't have installed several dependencies like git for example.

About the output, it generates. Avalon patch and simply finish saving the trace. It is true that it could not run the tests, but even with that it shows the change as a git patch and finishes.

**Comment by joskfg** [comment]
Ok, I think I've foudn the answer usign the inspector (which is undocumented in the root readme.md AFAIK). The result is:

```
**** Run Stats ****
Instance Cost: $0.39
Tokens Sent: 37,099
Tokens Received: 484
API Calls: 5

Evaluation results not found
```

So it doesn't generate the PR. I'll try again.

**Comment by joskfg** [comment]
After going deeper I see that the agent clones the repository and applies the patch inside the docker, but that code disappears instantly because the docker container stops and the code is not in a volume and the code is not creating any branch nor pushing the changes to the repository.

**Comment by joskfg** [comment]
After talking in discord and the related issue I see that currently is something not implement, so I close the issue. Thanks!
