### ISSUE TITLE
Inference - AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by steventangbc** [princeton-nlp/SWE-agent#40]
# From usage guide on inference in readme #
python run.py --model_name gpt4 --data_path https://github.com/pvlib/pvlib-python/issues/1603 --config_file config/default_from_url.yaml

Parsing command file: config/commands/defaults.sh
Parsing command file: config/commands/search.sh
Parsing command file: config/commands/edit_linting.sh
Parsing command file: config/commands/_split_string.py
Parsing command file: config/commands/defaults.sh
Parsing command file: config/commands/search.sh
Parsing command file: config/commands/edit_linting.sh
Parsing command file: config/commands/_split_string.py
INFO     📙 Arguments: agent:
...
INFO     💽 Loaded dataset from https://github.com/pvlib/pvlib-python/issues/1603

Traceback (most recent call last):
line 140, in __enter__
    signal.signal(signal.SIGALRM, self.handle_timeout)
AttributeError: module 'signal' has no attribute 'SIGALRM'

# Maybe incompatible version of Python on Docker image? #
python --version
Python 3.9.19

**Comment by klieret** [comment]
What's your OS? In #17, @cpendery mentioned that `signal.alarm` are UNIX specific. I'll see if we can get a solution today

**Comment by steventangbc** [comment]
Windows

**Comment by klieret** [comment]
You can now run swe-agent in a docker container on Windows. We still hope to have it run natively on Windows as well soon

**Comment by klieret** [comment]
This is now finally closed. Much thanks to @cpendery and sorry that it took so long to include this. The current fix checks whether we're on windows and then adds @cpendery's changes. I haven't enabled them by default because I still need to run over all of swe-bench to make sure it is 100% stable with the docker communication.
