### ISSUE TITLE
syntax  error in setup.sh { ./setup.sh: 9: Syntax error: "elif" unexpected (expecting "then") }

### ISSUE THREAD

**Issue by mo-ay** [princeton-nlp/SWE-agent#42]
I tried to run it on windows and on Linux both failed with error message { ./setup.sh: 9: Syntax error: "elif" unexpected (expecting "then") }

**Comment by AtakanG7** [comment]
Here is what I've done => 

Manuelly copy and paste from the setup.sh script the docker commands. Both for swe-agent and swe-eval. Not a proper solution but at least works.

**Comment by mo-ay** [comment]
```
 echo $SHELL
bash --version
```
/bin/bash
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by klieret** [comment]
Could you also give me more information about your operating system? Are you running from WSL?

The script runs fine for me. I also checked for unprintable characters, which are usually the prime suspect for things like this.

**Comment by mo-ay** [comment]
it didn't help, it shows deferent error  **: not found 2:
./setup.sh: 4: set: Illegal option -o pipefail**

**Comment by klieret** [comment]
> Could you also give me more information about your operating system? Are you running from WSL?

Can you also try to directly call bash on the script? `bash setup.sh`?

**Comment by mo-ay** [comment]
from bash windows 10: 
PS C:\Users\auser\swg\SWE-agent> bash setup.sh
setup.sh: line 2: $'\r': command not found
Setting up docker image for swe-agent...
setup.sh: line 9: syntax error near unexpected token `elif'
'etup.sh: line 9: `elif [[ "$arch" == "aarch64" || "$arch" == "arm64" ]]; then
----------------------
the updated setup.sh:
 bash setup.sh
setup.sh: line 2: $'\r': command not found
: invalid option name: pipefail

-------------- wsl 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

the error as mentioned before.
and with the new version Im getting:
./setup.sh
/usr/bin/env: ‘bash\r’: No such file or directory

and when I remove the #!/usr/bin/env bash I got:
./setup.sh: line 1: $'\r': command not found
: invalid option nameet: pipefail

**Comment by klieret** [comment]
Thanks for providing the information.

Let me ping @cpendery, he's running Windows as well. There's probably some more issues down the road, but I don't think this script here should fail on WSL...

**Comment by klieret** [comment]
Actually I'm very surprised that it says 

```
/usr/bin/env: ‘bash\r’: No such file or directory
```

This looks like Windows linebreaks to me. `because those are \r\n` and WSL will read `\n` as a linebreak, leaving you with `\r`. 

Did you manually copy the script into a text file or something like this?

**Comment by klieret** [comment]
To confirm, can you run `cat -e setup.sh`?

**Comment by klieret** [comment]
Great! :D
