### ISSUE TITLE
Run on local repositories

### ISSUE THREAD

**Issue by zachblume** [princeton-nlp/SWE-agent#43]
E.g.:
 - via cli string flag
 - via cli flag pointing to filename

Why:
 - will enable non-github workflows on top

**Comment by ofirpress** [comment]
sure sounds like a good idea. let's support this via file?

**Comment by ofirpress** [comment]
A lot of people are asking for this + supporting local Git repos. Let's discuss @klieret , but I think we should prioritize this.

**Comment by klieret** [comment]
Perhaps we could support a markdown file with a yaml header with metadata? Something like

```
---
local_repo_path: ...
setup_command: ...  # allow to install things in the container
---
I have an issue I run
```
this is code
```
blah blah
```

**Comment by ofirpress** [comment]
hmmm I think that would require more documentation reading from users. I think it's better to just accept a text/.md file and then accept the other things from other args in the run file.

I want to make the usage experience as easy as possible for new users

**Comment by klieret** [comment]
Adding additional command line options comes with a price though: The `run.py` interface is already complex. If we add more options that are only _sometimes_ relevant, it will lead to a lot of confusion with for example `--local_repo_path` being ignored depending on what you pass in as `--data_path`. In addition, these additional arguments also require users to read the documentation. 

The only other way (which might require a bit more work, but might be worthwhile) is to spilt up the CLI more into subcommands/different executables. 

For example a separate `solve-batch` (`swe-bench`-style evaluation-focused submissions), `solve-issue` (what we currently support with the issue path), `solve-local` (the new thing proposed here).

So then for example you'd do

```bash
python run.py solve-local --repo /path/to/repo --instructions /path/to/issue.md --install /path/to/setup.sh
```

and the command line options here wouldn't apply to `solve-batch` etc.

**Comment by klieret** [comment]
I think the split-into-subcommands approach is actually the best one. Every other strategy will run into a wall eventually.

**Comment by cschubiner** [comment]
people just want to try this out on their own code -- not having to go thru the whole github issue madness ideally

**Comment by klieret** [comment]
@cschubiner You can already check out #193 and run it locally. It will be merged very soon.
