### ISSUE TITLE
Replace `os.path` with `pathlib`

### ISSUE THREAD

**Issue by klieret** [princeton-nlp/SWE-agent#445]
`os.path` is cumbersome. Let's default to using `pathlib` everywhere. Most conversions can probably be done by copilot.

Once done, add [these ruff checks](https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth) to make sure it stays that way.

**Comment by rgsuhas** [comment]
Hi there 

I'd like to know if this issue has already been resolved, or if I can help by making the necessary changes.

Please let me know if I can contribute to this task.

Thanks,

**Comment by klieret** [comment]
you can just search the codebase if there's a few more instances remaining

**Comment by rgsuhas** [comment]
Ohhh
Thank you I will check 😂
