### ISSUE TITLE
Are you using function calling? 

### ISSUE THREAD

**Issue by JeremyAlain** [princeton-nlp/SWE-agent#450]
### Describe the issue

Am i right in assuming that currently SWE-agent parses tool calls etc. manually and then calls the tools? i.e. currently you are not using the function calling option e.g. of openai (https://platform.openai.com/docs/guides/function-calling)?

**Comment by klieret** [comment]
This is correct, we don't use it at the moment, we simply extract the triple-backticks blocks from the LM answer and treat the content as the commands.

**Comment by ofirpress** [comment]
From what I remember, J & C tried tool calling and it did not improve performance.
