### ISSUE TITLE
Cost of running GPT-4 on the SWE-bench lite benchmark

### ISSUE THREAD

**Issue by nnWhisperer** [princeton-nlp/SWE-agent#452]
### Describe the issue

Hello, I want to benchmark on the swe bench lite dataset, hence I'd like to know how much is the total cost would be for gpt-4. Unlike working for a research facility that are offered credits, for us the cost would be an important factor. That cost would also be a nice thumb rule to compare against when benchmarking for other LLMs. Thank you

**Comment by ofirpress** [comment]
You can just set the cost limit per issue to be 3 and then it won't ever cost you more than 3*300 dollars. Average is probably closer to 2 dollars so it would come out to ~$600.
