### ISSUE TITLE
Does it read documentation?

### ISSUE THREAD

**Issue by Am0stafa** [princeton-nlp/SWE-agent#459]
### Describe the feature

I think it would improve the quality if the model first goes for example to the package.json and searches the web for the documentation of each library used then vector embeds them to be used to solve the problem.
What do you think?

### Potential Solutions

We can discuss that and if applicable I can make this contribution

**Comment by ofirpress** [comment]
not yet. If you implement this, run it on swe-bench lite, and if it improves performance we will integrate it into swe-agent
