### ISSUE TITLE
CodeCov includes tests folder

### ISSUE THREAD

**Issue by li-boxuan** [princeton-nlp/SWE-agent#470]
https://app.codecov.io/gh/princeton-nlp/SWE-agent

<img width="1581" alt="image" src="https://github.com/princeton-nlp/SWE-agent/assets/25746010/378fced6-fc01-4a85-8e15-6c41fc81dcef">

It seems tests folder is counted towards code coverage. There are pros & cons for doing so - my take from https://about.codecov.io/blog/should-i-include-test-files-in-code-coverage-calculations/ is they should be in general not included.

I suppose the tests folder was just included by accident - unless you really want to include the "test coverage for tests".

**Comment by klieret** [comment]
Thanks for the suggestion!

I gave this some thought and decided to leave it as-is after having a more complicated test (that has some asserts in hooks to the other classes) seemingly pass even though the hooks didn't properly fire.

It's more important to me to make sure all the tests do what they should than to get a cleaner interpretation of what the coverage % means.
