### ISSUE TITLE
Web UI: Startup script immediately fails on macOS in ZSH or stock Bash environments.

### ISSUE THREAD

**Issue by kwight** [princeton-nlp/SWE-agent#480]
### Describe the bug

When running `./start_web_ui.sh` on macOS in ZSH or stock Bash (v3.2.57), the script exits immediately due to the `wait -n` call; `-n` is an unsupported flag in these environments (it was introduced in Bash 4, and ZSH has never supported it). Since ZSH is now the default shell on macOS, and stock Bash can't be upgraded directly, macOS users who are not using an external version of Bash would likely hit this bug.

Removing the `-n` flag allows the script to run as expected (without the proper `wait` behaviour of course).

Some possible "solutions":
* State Bash >= 4.3 as a project requirement (macOS users should be able to achieve this with Homebrew `brew install bash`).
* Remove the `-n` flag, which would then mean `wait` would wait for all background process to complete. Maybe this is fine – does `pm2` count as a background process? Not sure.
* Wait on just the Flask process by PID.

### Steps/commands/code to Reproduce

1. `python3 -m venv venv`
2. `source venv/bin/activate`
3. `pip3 install -e .`
4. `./start_web_ui.sh`

### Error message/results

```
up to date, audited 1820 packages in 1s

349 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (2 moderate, 6 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[PM2] Starting /Users/kwight/Code/SDKs/n/bin/npm in fork_mode (1 instance)
[PM2] Done.
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ swe-agent          │ fork     │ 0    │ online    │ 0%       │ 880.0kb  │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
* If you are running on your own machine, then a browser window 
  should have already opened. If not, wait a few more seconds, then 
  open your browser at http://localhost:3000
* If you are running in github codespaces, please click the popup 
  that offers to forward port 3000 (not 8000!).
  Missed it? Find more information at 
  https://princeton-nlp.github.io/SWE-agent/installation/codespaces#running-the-web-ui
* Something went wrong? Please check 
  web_api.log for error messages!
./start_web_ui.sh: line 38: wait: -n: invalid option
wait: usage: wait [n]
Something went wrong. Here's web_api.log:
----------
----------
Stopping react server
[PM2] Applying action deleteProcessId on app [swe-agent](ids: [ 0 ])
[PM2] [swe-agent](0) ✓
```

### System Information

Mac Studio, M2 Max chipset, 96GB RAM
MacOS Sonoma 14.5
Python 3.12.2

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
The current solution is still not great, because as you suspected `pm2` isn't actually a background process, so if the react server dies, the script doesn't die. 

I played around with something like this:

```
#!/usr/bin/env bash

set -euo pipefail

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function on_exit () {
    kill -SIGTERM $pid1 $pid2
    echo "Exiting. Here's the log from the flask backend:"
    echo "----------"
    if [ -f "web_api.log" ]; then
        cat web_api.log
    fi
    echo "----------"
    echo "Here's the log from the react frontend:"
    echo "----------"
    if [ -f "web_frontend.log" ]; then
        cat web_frontend.log
    fi
    echo "----------"
    sleep 0.5
    kill -KILL $pid1 $pid2 2>/dev/null
}

trap on_exit EXIT
#trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

python sweagent/api/server.py > web_api.log 2>&1 &
pid1=$!

cd "${this_dir}/sweagent/frontend"
npm install
npm start > ../../web_frontend.log 2>&1 &
pid2=$!
cd ../../

echo $pid1 $pid2

echo "* If you are running on your own machine, then a browser window "
echo "  should have already opened. If not, wait a few more seconds, then "
echo "  open your browser at http://localhost:3000"
echo "* If you are running in github codespaces, please click the popup "
echo "  that offers to forward port 3000 (not 8000!)."
echo "  Missed it? Find more information at "
echo "  https://princeton-nlp.github.io/SWE-agent/installation/codespaces#running-the-web-ui"
echo "* Something went wrong? Please check "
echo "  web_api.log for error messages!"

sleep 0.5

while true; do
    if ! kill -0 $pid1 2>/dev/null; then
        echo "API exited"
        exit 1
    elif ! kill -0 $pid2 2>/dev/null; then
        echo "Frontend exited"
        exit 2
    fi
    sleep 0.5
done

wait
```

but this didn't immediately seem to work either.

**Comment by klieret** [comment]
Let's close this issue in favor of https://github.com/princeton-nlp/SWE-agent/issues/488

**Comment by kwight** [comment]
> but this didn't immediately seem to work either with the cleanup.

@klieret Indeed, I tried a couple things like that too with no success. At least as things are now on `main`, it's not a brick wall any more for macOS ZSH users (it all fires up now 🔥). Thanks!
