### ISSUE TITLE
How to use local Ollama models?

### ISSUE THREAD

**Issue by anuraagdjain** [princeton-nlp/SWE-agent#5]
Hello, I'm trying to figure out how should I provide the model_name for Ollama models which are in my local machine. I am already running Ollama and have mistral installed. 

```bash
python run.py --model_name ollama/mistral --data_path <github issue url>
```

**Comment by carlosejimenez** [comment]
You should run it with `--host_url localhost:11434` (or whatever it is) and `--model_name ollama:mistral`.
Support for ollama models is still a bit experimental, so please let us know if you experience any issues!

**Comment by anuraagdjain** [comment]
> You should run it with `--host_url localhost:11434` (or whatever it is) and `--model_name ollama:mistral`. Support for ollama models is still a bit experimental, so please let us know if you experience any issues!

Changing to `ollama:mistral` worked, I'll post if I find any errors. But this looks good, solid work 👏
