### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by alfi4000** [princeton-nlp/SWE-agent#51]
Would it be possible that you guys add Ollama support? or is it already in progress?

**Comment by klieret** [comment]
This is already supported, see #5 . There was a small bug with Ollama that was fixed in #49.

**Comment by alfi4000** [comment]
And how to use it within the docker I mean the --host_url localhost:11434  --model_name ollama:mistral commands what do I have to modify?

**Comment by klieret** [comment]
those should be arguments to `run.py`

**Comment by alfi4000** [comment]
Ahh ok so it is not for Docker!

**Comment by alfi4000** [comment]
Nevermind it looks like it is docker based the hole project, I am fine thanks!
