### ISSUE TITLE
The Docker Setup Looks a bit weird why do I need to create a condo environment?

### ISSUE THREAD

**Issue by alfi4000** [princeton-nlp/SWE-agent#52]
The Docker Setup Looks a bit weird why do I need to create a condo environment?

**Comment by klieret** [comment]
Not sure what you mean with the docker setup looking weird, but here's the [instructions](https://github.com/princeton-nlp/SWE-agent?tab=readme-ov-file#-setup-) for how to install the software ;)

**Comment by alfi4000** [comment]
Its because I am very new to docker and don't understand because it is the first time I need to create a condo environment, I am interested why what the reason for that is because python packages?
