### ISSUE TITLE
Allow to use different port for backend

### ISSUE THREAD

**Issue by ofirpress** [princeton-nlp/SWE-agent#550]
i'm hearing this might be an issue if someone already has something running on 8000.

**Comment by klieret** [comment]
Could probably do something like this for setting the proxy between backend to frontend https://stackoverflow.com/questions/39649298/set-proxy-in-package-json-to-env-variable/71312471#71312471

**Comment by ofirpress** [comment]
Not sure how important this is but carlos said it could be useful. only do this if it's easy
