### ISSUE TITLE
Linter should only block editing because of *new* errors, not pre-existing ones

### ISSUE THREAD

**Issue by ofirpress** [princeton-nlp/SWE-agent#560]
There is a small bug right now:

If a file in a cloned repo has existing linting errors, it will be impossible to edit other parts of it (the linter will complain about the broken parts).

Therefore, the linter should run *before* applying any changes and it should only block editing if *new* errors have been introduced. any *existing* errors should just lead to a warning, not a block.

thank you.
please tell me if I need to clarify

**Comment by klieret** [comment]
That makes sense. Shouldn't be hard to do. Except that all the commands are implemented in bash (guess they started simple, but are now getting more complicated), so it's probably gonna be a bit ugly.
