### ISSUE TITLE
How does SWE-agent parse files?

### ISSUE THREAD

**Issue by ivan4722** [princeton-nlp/SWE-agent#567]
### Describe the issue

I was just wondering how SWE-agent parses the file tree of github repositories. Does it place emphasis on file names? How does it efficiently parse through files (especially long files)? 
I would also appreciate it if you could show me which file contains the code to do said action. 
Thanks!

**Comment by klieret** [comment]
SWE-agent uses relatively simple `find` and `grep`-style commands. See [our docs](https://princeton-nlp.github.io/SWE-agent/config/commands/) for commands. You can also check the trajectories from SWE-agent [here](https://github.com/swe-bench/experiments/) to see it in action without running it yourself.
