### ISSUE TITLE
OPENAI_API_BASE_URL with port - semi colon issue

### ISSUE THREAD

**Issue by shuther** [princeton-nlp/SWE-agent#569]
### Describe the bug

in the keys.cfg file, the line below is not supported:
`OPENAI_API_BASE_URL:http://192.168.0.120:4000`

### Steps/commands/code to Reproduce

`OPENAI_API_BASE_URL:http://192.168.0.120:4000`

### Error message/results

```
app-1     | During handling of the above exception, another exception occurred:
app-1     |
app-1     | Traceback (most recent call last):
app-1     |   File "/app/sweagent/utils/config.py", line 45, in __init__
app-1     |     self._keys_cfg = config_file.Config(str(keys_cfg_path))
app-1     |   File "/usr/local/lib/python3.9/site-packages/config/__init__.py", line 707, in __init__
app-1     |     self.load_file(stream_or_path, kwargs.get('encoding'))
app-1     |   File "/usr/local/lib/python3.9/site-packages/config/__init__.py", line 816, in load_file
app-1     |     self.load(f)
app-1     |   File "/usr/local/lib/python3.9/site-packages/config/__init__.py", line 807, in load
app-1     |     raise cfe
app-1     | config.ConfigFormatError: Unexpected ':' at (2, 25)
app-1     |
app-1     | The above exception was the direct cause of the following exception:
app-1     |
app-1     | Traceback (most recent call last):
app-1     |   File "/app/run.py", line 44, in <module>
app-1     |     from sweagent.agent.agents import Agent, AgentArguments
app-1     |   File "/app/sweagent/agent/agents.py", line 16, in <module>
app-1     |     from sweagent.agent.models import (
app-1     |   File "/app/sweagent/agent/models.py", line 22, in <module>
app-1     |     from sweagent.utils.config import keys_config
app-1     |   File "/app/sweagent/utils/config.py", line 85, in <module>
app-1     |     keys_config = Config()
app-1     |   File "/app/sweagent/utils/config.py", line 48, in __init__
app-1     |     raise RuntimeError(msg) from e
app-1     | RuntimeError: Error loading keys.cfg from /app/keys.cfg. Please check the file.
```

### System Information

ubuntu with dockers

### Checklist

- [X] I'm running with the latest docker container/on the latest development version
- [X] I've searched the other issues for a duplicate
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
I believe you're missing the quotation marks.
