### ISSUE TITLE
Support for Retrieval-Augmented Generation (RAG) in SWE Agent

### ISSUE THREAD

**Issue by zixuanzhang226** [princeton-nlp/SWE-agent#575]
### Describe the issue

Hello,

Does the SWE agent community have any plans to support Retrieval-Augmented Generation (RAG)? Our team is interested in implementing RAG functionality. We would like to know if you have any suggestions on where we could add the documents so that questions and documents can be processed by the generator to craft a response.

Thank you!

**Comment by ofirpress** [comment]
The agent has 3 different search functions in it already. You could just add additional ones and test if they improve performance on the dev set. Does that answer your q?

**Comment by zixuanzhang226** [comment]
Thank you for your response! Would you please show me where the 3 different search functions are? Thank you very much!

**Comment by ofirpress** [comment]
<img width="551" alt="image" src="https://github.com/princeton-nlp/SWE-agent/assets/20109662/bf09f53a-6cc3-4fac-a7fa-33a28dc9e104">

**Comment by zixuanzhang226** [comment]
I think the RAG functionality that we want to implement is different from the 3 different search functions already in there. We want to make it able to retrieve documents to generate responses. Here is how I approach it: 
<img width="1033" alt="Screenshot 2024-06-17 at 4 07 21 PM" src="https://github.com/princeton-nlp/SWE-agent/assets/171880989/1cd97b2f-2d15-4127-9999-1dfa26ea4ea7">
I may also need to make changes to the INSTRUCTIONS and IMPORTANT TIPS. Do you think it’s the correct way to implement it? Thank you!

**Comment by ofirpress** [comment]
yes add a command and add an instruction and/or tip. if you add it to the demonstration trajectory that would also be helpful

**Comment by klieret** [comment]
We're definitely happy to add more commands to SWE-agent. In order to make them available to the _default_ config, we'd need a study to show that it actually helps performance, but this is not needed to add the functionality as an option.

**Comment by zixuanzhang226** [comment]
Hello, I would like to implement my own command for the SWE-agent using a Python file. However, I looked through the example of filemap.py but it seems like doesn't actually work as a command. (as it isn't registered under the command_files in the default_from_url.yaml) Not really sure how it works. Do you have more detailed instructions of how to add a Python file as a command please?
