### ISSUE TITLE
How to run SWE-agent on gpt 3.5?

### ISSUE THREAD

**Issue by ivan4722** [princeton-nlp/SWE-agent#605]
### Describe the issue

Hi, I modified the command from the documentation to try and run on 3.5, but it does not run.
I tried
```
python run.py --model_name gpt-3.5 --per_instance_cost_limit 2.00 --config_file ./config/default.yaml --split test
```
and 
```
python run.py --model_name gpt3.5 --per_instance_cost_limit 2.00 --config_file ./config/default.yaml --split test
```
and 
```
python run.py --model_name gpt-3.5-turbo --per_instance_cost_limit 2.00 --config_file ./config/default.yaml --split test
```

**Comment by ofirpress** [comment]
You have the list of available models here: https://github.com/princeton-nlp/SWE-agent/blob/d71f1f5eeb7631acdbdbfaa0938c6519af2cbc70/sweagent/agent/models.py#L179
