### ISSUE TITLE
Improve "RuntimeError: Image sweagent/swe-agent:latest not found. Please ensure it is built and available. Please double-check that you followed all installation/setup instructions from the readme." error

### ISSUE THREAD

**Issue by samuela** [princeton-nlp/SWE-agent#620]
### Describe the feature

When running swe-agent for the first time, I am faced with
```
  RuntimeError: Image sweagent/swe-agent:latest not found. Please ensure it is built and available. Please double-check that you followed all installation/setup instructions from the readme.
```
This error message provides little context on what is wrong and how to move forward.

### Potential Solutions

* Automatically build the `sweagent/swe-agent:latest` image if it is not found
* Link to the documentation that the error message is referencing

**Comment by ofirpress** [comment]
This is for installation with docker? If this doesn't work, shouldn't users just try the non-docker install?

**Comment by locona** [comment]
For reference, here's how I improved mine.

I ran docker pull latest again and docker run and it worked fine

**Comment by samuela** [comment]
> This is for installation with docker? If this doesn't work, shouldn't users just try the non-docker install?

This is for the source install, but afaiu regardless of installation approach trajectories are evaluated within `sweagent/swe-agent:latest` containers.

**Comment by klieret** [comment]
Yup, @samuela is right, we could make the error message nicer (and yes, this is for all installation variants). And yes @locona , that's the way to resolve it :)

Gonna improve this as @samuela suggested soon
