### ISSUE TITLE
Run on a local directory (instead of GitHub issue)

### ISSUE THREAD

**Issue by agamm** [princeton-nlp/SWE-agent#63]
It would be great if it could run on a local directory and suggest a new git branch so I could compare the changes + request a change without needing github and a repo.

PS. Right now I don't know how to actually make changes from `run.py` it outputted some terminal logs but I can't reasonably use them for anything.

**Comment by klieret** [comment]
Thanks for the suggestion, but duplicate of #57 and #43.
