### ISSUE TITLE
How to install this amazing agent only in conda environment(whitout docker)?

### ISSUE THREAD

**Issue by 443127316** [princeton-nlp/SWE-agent#633]
### Describe the issue

Hi, thanks for providing this amazing agent frame. Do you have a plan to provide an installation doc with only conda environment.

**Comment by klieret** [comment]
Running swe-agent without docker will not be possible, as SWE-agent is using docker containers as a sandbox to run LM-generated code. This is both a safety feature and makes it easier to run swe-agent with arbitrary environments.
