### ISSUE TITLE
AZURE OPENAI API KEY

### ISSUE THREAD

**Issue by yanivvak** [princeton-nlp/SWE-agent#639]
### Describe the bug

Hi,
I'm trying to run swe with azure credentials I got this error,
KeyError: 'Key OPENAI_API_KEY not found in environment variables or keys.cfg (if existing)'

My Keys.cfg :
GITHUB_TOKEN: 'xx'
AZURE_OPENAI_API_KEY: xx'
AZURE_OPENAI_ENDPOINT: 'xx'
AZURE_OPENAI_DEPLOYMENT: 'gpt-4o'
AZURE_OPENAI_API_VERSION: '2024-05-01-preview'

### Steps/commands/code to Reproduce

./start_web_ui.sh

### Error message/results

 ''' a'''

### System Information

MAC M2

### Checklist

- [X] I'm running with the latest docker container/on the latest development version (this means running both `git pull` and `docker pull sweagent/swe-agent:latest`)
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
Ah, to use the azure models, you need to specify the model like `--model azure:gpt4` (though the model itself will be set by `AZURE_OPENAI_DEPLOYMENT`).
