### ISSUE TITLE
How does SWE-agent find the issue # or pull request # to fix the bug?

### ISSUE THREAD

**Issue by ivan4722** [princeton-nlp/SWE-agent#640]
### Describe the issue

I'm currently trying to prompt the agent to generate dependency graphs, and the agent is able to execute the curl command accordingly. 
The command looks like this ```./generate_graph.sh pytest 7490 pytest-dev``` and the middle number is supposed to be the PR # that is extracted from the instance id.
However, when I run the agent, it runs like this: 
```
ACTION (primary)
generate_graph pytest placeholder pytest-dev
```
or mentions that a PR # was not provided.

Is there anywhere I should look to see how the agent finds the PR # or issue # to be fixed? I'm a little confused because the PR # is explicitly stated in the dataset, and I assume that dataset is fed to the agent.

Thank you!

**Comment by klieret** [comment]
The number in the instance ID (e.g., `"django__django-16379"`) is the number of the PR, so you could use that. But the agent of course has all of the information from the dataset that it loads (the `--data_path` file which loads SWE-bench light dev-set by default).

**Comment by ivan4722** [comment]
> The number in the instance ID (e.g., `"django__django-16379"`) is the number of the PR, so you could use that. But the agent of course has all of the information from the dataset that it loads (the `--data_path` file which loads SWE-bench light dev-set by default).

Right, I was using that to get the PR # for my own experimentation. However, the agent seems confused and does not know where to get the PR number, is there a specific code file where it is broken down? I was just wondering how it was handled in the backend

**Comment by ivan4722** [comment]
More so asking how to prompt the agent to use that number

**Comment by ivan4722** [comment]
Currently I have 
```
        instance_id = self.env.data[index]["instance_id"]
        # Extract and print the PR number
        pr_number = instance_id.split('-')[-1]
```
And 
```
setup_args = {"issue": issue, "files": files, "test_files": test_files, "tests": tests, "pr_number": pr_number }
```
However the agent still seems to be confused
