### ISSUE TITLE
Which Python version to use?

### ISSUE THREAD

**Issue by anupamme** [princeton-nlp/SWE-agent#643]
### Describe the bug

I tried installing SWE-bench with various python version: 3.8, 3.9, 3.10, 3.11 and 3.12.

The requirements.txt lists this package: config

If you goto the package [url](https://pypi.org/project/config/) you will see it is only supported till python 3.7.

The package config uses a package pysqlite which is not supported in python 3 instead there is an inbuilt package called sqlite3.

So my question is which python version are we supposed to use?

Is it possible to not use the package config as it is not supported in later versions of python?

The error stack I get when I pip install is this:

Collecting pysqlite (from config->sweagent==0.6.1)
Using cached https://pypi.uberinternal.com/packages/packages/42/02/981b6703e3c83c5b25a829c6e77aad059f9481b0bbacb47e6e8ca12bd731/pysqlite-2.8.3.tar.gz (80 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Steps/commands/code to Reproduce

pip3.13 install -r requirements.txt

or

pip3.12 install config

will result in following exception:

### Error message/results

Collecting pysqlite (from config->sweagent==0.6.1)
Using cached https://pypi.uberinternal.com/packages/packages/42/02/981b6703e3c83c5b25a829c6e77aad059f9481b0bbacb47e6e8ca12bd731/pysqlite-2.8.3.tar.gz (80 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### System Information

Mac M2, macOS Sonoma 14.5, python 3.12 (3.11, 3.10, 3.9, 3.8)

### Checklist

- [X] I'm running with the latest docker container/on the latest development version (this means running both `git pull` and `docker pull sweagent/swe-agent:latest`)
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
It sounds like you wanted to install SWE-bench. This is the SWE-agent repository.

**Comment by klieret** [comment]
It also does NOT depend on `pysqlite` (if you go to pypi and download the package files, you can search for `sqlite` and you'll find nothing).

I'm really not sure what's going on with your python distribution. Are you pulling from a different index-url instead of pypi or something?

**Comment by anupamme** [comment]
I'm pointing to a different index-url of pypi, perhaps that is the reason I'm getting this version of config. Appreciate your response.
