### ISSUE TITLE
Does it only support Python?

### ISSUE THREAD

**Issue by Xylon2** [princeton-nlp/SWE-agent#651]
### Describe the issue

When I try to run it I get
`Error: Install command failed to execute successfully: Obtaining file:///Xylon2__todefer ERROR: file:///Xylon2__todefer does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`

My project is not Python it's Clojure.

**Comment by Xylon2** [comment]
If it only supports Python perhaps you could mention that in the README?

**Comment by klieret** [comment]
I'm honestly surprised that it tried to run `pip install` or something. What command did you run?  As discussed in #53, it should probably be still possible to run on a different language, even though some helpful tools (like the linting) will not be enabled.

**Comment by klieret** [comment]
If you believe there is a bug, please open a bug report and I can investigate (I have tried but could not reproduce your error, unless you directly specified `--environment_setup` with a python setup script).

**Comment by Xylon2** [comment]
OK I tried again and it worked. Not sure what happened before.

**Comment by klieret** [comment]
Great to hear that & thanks for checking :)  @Xylon2
