### ISSUE TITLE
How does SWE-Agent have access to setup args

### ISSUE THREAD

**Issue by ivan4722** [princeton-nlp/SWE-agent#652]
### Describe the issue

from run.py:
```
        setup_args = {"issue": issue, "files": files, "test_files": test_files, "tests": tests, "pr_number": pr_number }
        print(setup_args)
        info, trajectory = self.agent.run(
            setup_args=setup_args,
            env=self.env,
            observation=observation,
            traj_dir=self.traj_dir,
            return_type="info_trajectory",
        )
```
Trying to pass an additional parameter ```pr_number``` to the agent, but the agent does not seem to have access to it, is there anything else I have to do in the environment setup?

Thanks.

**Comment by klieret** [comment]
> , but the agent does not seem to have access to it, 

Not really sure what you mean here. You want to use it in a template? The `setup_args` are not exposed as env variables if this is what you're asking. You'd have to modify the code for that.
