### ISSUE TITLE
Implement Feature to Handle User Input Markup Text for Feature Requests in SWE

### ISSUE THREAD

**Issue by SyedMuqtasidAli** [princeton-nlp/SWE-agent#656]
### Describe the feature

Currently, the SWE tool is designed to work exclusively with GitHub issues URLs for debugging purposes. I would like to enhance the SWE tool to accept user input in the form of markup text, treating it as a feature request rather than a debugging task. This new functionality should enable users to provide detailed feature requests directly through a markup text form.

Here is an example of the markup text format for a feature request:

TaskName: Implement Basic Math Addition Function
KnowledgeGraph:
  Function: adds Numbers
  Numbers: consists of Integer values
CodeBase:
  Type: Simple Function
  Language: Python
DesignKeyTradeOffs:
  - option: Use Simple Addition Logic
    pros:
      - Straightforward to implement
      - Efficient for basic mathematical operations
    cons:
      - Limited to basic arithmetic without extended functionality
DesignPattern:
  - Functional Programming for clear and concise implementation
FilesCRUD:
  add_numbers.py: Create
Design:
  Develop add_numbers.py to perform addition of two integers
  Include input validation to ensure only integers are processed
DesignConstraints:
  - Function must be optimized for quick computation
  - Should be capable of being incorporated into larger mathematical modules or systems
ImplementationBestPractices:
  - Follow PEP 8 style guide for Python code
  - Use clear and meaningful variable names
  - Implement exception handling for type errors and overflow scenarios
RiskMitigation:
  - Implement checks to ensure that only numbers are added
  - Provide clear error handling for non-integer inputs
TestStrategy:
  UnitTests:
    - Test the addition of two positive integers
    - Test the addition of a positive and a negative integer
    - Test the addition of two negative integers
    - Test input validation to reject non-integer types
EstimatedLinesOfCode: 20

### Potential Solutions

Markup Text Parsing:

Implement a parser to process the markup text format, extracting relevant information such as task name, knowledge graph, code base, design key trade-offs, design pattern, files CRUD operations, design details, design constraints, implementation best practices, risk mitigation strategies, test strategy, and estimated lines of code.
Ensure the parser validates the input to confirm adherence to the expected markup format.
User Interface Enhancement:

Modify the existing user interface to include an input field for markup text.
Provide guidance and templates to users on how to format their feature requests correctly.
Feature Request Handling:

Extend the SWE tool's functionality to distinguish between debugging tasks (from GitHub issues URLs) and feature requests (from markup text input).
Implement logic to process and store feature requests, allowing for tracking and prioritization within the SWE tool.
Feedback Mechanism:

Develop a feedback system that provides users with confirmation and status updates regarding their submitted feature requests.
Integrate notifications or alerts to keep users informed about the progress of their requests.
By implementing these solutions, the SWE tool will be more versatile, enabling users to submit and manage feature requests efficiently through a structured markup text format. This enhancement will improve the overall user experience and streamline the process of requesting new features.

**Comment by klieret** [comment]
You can already specify a markdown or text file as input with `--data_path`, see [the docs](https://princeton-nlp.github.io/SWE-agent/usage/cl_tutorial/#specifying-the-repository). So nothing is stopping you from directly ingesting the file that you describe.
