### ISSUE TITLE
How to replicate results for SWE-Bench with SWE-agent?

### ISSUE THREAD

**Issue by code2graph** [princeton-nlp/SWE-agent#67]
How can I replicate results for SWE-Bench with SWE-agent? Can you add detailed setup steps?

**Comment by code2graph** [comment]
I see bunch of scripts here: https://github.com/princeton-nlp/SWE-agent/tree/main/scripts.

But no clear direction how to replicate it.

**Comment by code2graph** [comment]
@karthikncode please help.

**Comment by klieret** [comment]
Let me close this issue in favor of #88
