### ISSUE TITLE
Building eval docker failed: COPY failed: forbidden path outside the build context: ../evaluation/evaluation.py ()

### ISSUE THREAD

**Issue by lilitttaa** [princeton-nlp/SWE-agent#68]
An error occurred when I ran bash setup.sh on WSL:
```
Step 1/5 : FROM swe-agent
 ---> 4d60329db014
Step 2/5 : COPY ../evaluation/evaluation.py /evaluation.py
COPY failed: forbidden path outside the build context: ../evaluation/evaluation.py ()
```

**Comment by maxfinnsjo** [comment]
I got this error, on Arch Linux, when I ran it too.

**Comment by klieret** [comment]
The `eval.Dockerfile` seems to be just a thin wrapper around `swe-bench`. Were you following any specific instructions when installing it?

The error itself can probably be fixed quite easily by changing the line to

```
COPY evaluation/evaluation.py /evaluation.py
```

and then calling docker from the base directory as follows

```bash
docker build -f docker/eval.Dockerfile .
```

**Comment by klieret** [comment]
Actually the container is built by `./setup.sh` which runs `docker build -f docker/eval.Dockerfile .` from the base directory, so I think everything works as intended. I'll put a note in the dockerfile to avoid people mistakenly trying to build it from the `docker` dir.
