### ISSUE TITLE
setup/configuration issues on apple m3

### ISSUE THREAD

**Issue by michaeljabbour** [princeton-nlp/SWE-agent#686]
### Describe the feature

installation and use is unnecessarily complex

### Potential Solutions

-simple terminal or terminal docker deployment
-models should be a drop down
-keys.cfg should be in the repo with correct permissions and format
-ability to set API configs and test in the interface
-graphical connections to github to identify correct repo and branch
-ability to address port conflict if something is running on 3000, 3001, etc.

**Comment by klieret** [comment]
That's a lot things for one issue, but thank you for the suggestions ;)  

Regarding the web GUI: We currently don't have enough personpower to work on improving this. Though I would probably accept simple PRs to improve things.

Therefore I'll have to close this issue.

> -simple terminal or terminal docker deployment

We do have a terminal interface if that's the question.

The port thing is #550 (you can switch the port of the frontend, but not of the backend atm)

**Comment by michaeljabbour** [comment]
Hi @klieret - I'm happy to contribute code to support these changes over time if that is of interest.
