### ISSUE TITLE
Is Creating Patch in SWE Agent means issue is resolves? How do I ensure issue is resolved?

### ISSUE THREAD

**Issue by MAhmadUzair** [princeton-nlp/SWE-agent#708]
### Describe the issue

![issue](https://github.com/user-attachments/assets/2937a00e-cf35-4854-8488-fd164ffc85cd)

**Comment by ofirpress** [comment]
no, creating a patch means it thinks it resolved the issue, but sometimes it is wrong. you need to run swe-bench evaluation.

**Comment by MAhmadUzair** [comment]
Okayy!!!, How to run this swe-bench evaluation?
