### ISSUE TITLE
Can you write the command for SWE Bench, I could not understant about below statement

### ISSUE THREAD

**Issue by MAhmadUzair** [princeton-nlp/SWE-agent#713]
### Describe the issue

This is the command I have been using to run a single instance!! 

```
python run.py --model_name gpt4 \
  --instance_filter marshmallow-code__marshmallow-1359
```
More context is available on #711 issue.

What changes it require according to the below statement? Can you write one?
```
The above examples use the default value of --data_path (Princeton-nlp/SWE-bench_Lite, which will be looked up from huggingface). You can specify any other huggingface datasets as well, or supply the path to a pre-downloaded dataset. By default, the SWE agent evaluates the dev split of that dataset. You can change that by supplying the --split argument to the above commands (obviously you shouldn't tune your model on the test dataset).
```

Create an example command to run swebench.

For Single Instance:

For Full SWE Bench Lite:

Thanks.

**Comment by klieret** [comment]
It means that you need to be careful about which split of the dataset you're using (`dev` or `test`), because the default settings are different.
