### ISSUE TITLE
Found a mistake in SWE-Agent Documentation at Benchmarking Section

### ISSUE THREAD

**Issue by MAhmadUzair** [princeton-nlp/SWE-agent#714]
### Describe the bug

From Issue #711 There you explained this way to resolve the missing id from swebench lite.

```
Ahh, I see what's going on. marshmallow-code__marshmallow-1359 is in the dev split of SWE-B lite, which is the default for running SWE-a. However, the default split of SWE-B is test.

So you have to add the --split test to the SWE-B command.

Good question, I'll add it to the documentation.
```

I have run this but actually, there is a mistake, It should be ''--split dev" not ''--split test".

### Steps/commands/code to Reproduce

```
From Issue #711 There you explained this way to resolve the missing id from swebench lite.

```
Ahh, I see what's going on. marshmallow-code__marshmallow-1359 is in the dev split of SWE-B lite, which is the default for running SWE-a. However, the default split of SWE-B is test.

So you have to add the --split test to the SWE-B command.

Good question, I'll add it to the documentation.
```

I have run this but actually, there is a mistake, It should be ''--split dev" not ''--split test".
```

### Error message/results

```
From Issue #711 There you explained this way to resolve the missing id from swebench lite.

```
Ahh, I see what's going on. marshmallow-code__marshmallow-1359 is in the dev split of SWE-B lite, which is the default for running SWE-a. However, the default split of SWE-B is test.

So you have to add the --split test to the SWE-B command.

Good question, I'll add it to the documentation.
```

I have run this but actually, there is a mistake, It should be ''--split dev" not ''--split test".
```

### System Information

Windows i7 8th

### Checklist

- [X] I'm running with the latest docker container/on the latest development version (this means running both `git pull` and `docker pull sweagent/swe-agent:latest`)
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
You're right, it should be `--split dev` when you want to evaluate on a dev set instance. It just has to match.
