### ISSUE TITLE
Duplicate code in Utils to check for a "single instance"

### ISSUE THREAD

**Issue by pdemro** [princeton-nlp/SWE-agent#728]
### Describe the bug

Notwithstanding the dubious comment reporting "very brittle logic", I am reporting what I believe is duplicate code in the `Utils.py` file (below).  

### Steps/commands/code to Reproduce

The following code block:

```
    # The next if statement is very brittle logic to determine if we're processing a single instance
    if (
        file_path.startswith("text://")
        or (Path(file_path).is_file() and Path(file_path).suffix in [".md", ".txt"])
        or is_github_issue_url(file_path)
    ):
        ib = InstanceBuilder(token=token)
        ib.set_problem_statement(file_path)
        if repo_path:
            ib.set_repo_info(repo_path, base_commit=base_commit)
        elif is_github_repo_url(file_path):
            ib.set_repo_info_from_gh_url(file_path, base_commit=base_commit)
        else:
            msg = f"Could not determine repo path from {file_path=}, {repo_path=}"
            raise ValueError(msg)

        return [ib.build()]
```

Is identical logically to:

```
    # The next if statement is very brittle logic to determine if we're processing a single instance
    if (
        (Path(file_path).is_file() and Path(file_path).suffix in [".md", ".txt"])
        or is_github_issue_url(file_path)
        or file_path.startswith("text://")
    ):
        ib = InstanceBuilder(token=token)
        ib.set_problem_statement(file_path)
        if repo_path:
            ib.set_repo_info(repo_path, base_commit=base_commit)
        elif is_github_repo_url(file_path):
            ib.set_repo_info_from_gh_url(file_path)
        else:
            msg = f"Could not determine repo path from {file_path=}, {repo_path=}"
            raise ValueError(msg)

        return [ib.build()]
```

### Error message/results

n/a

### System Information

n/a

### Checklist

- [X] I'm running with the latest docker container/on the latest development version (this means running both `git pull` and `docker pull sweagent/swe-agent:latest`)
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
This was introduced in https://github.com/princeton-nlp/SWE-agent/pull/317/files#diff-b24a4d7213e40c6b304daeb27a324ff87a7366285920dc6060b38cc96087ce4c . Clearly a mistake and I didn't catch it when reviewing.

Thanks for spotting this!
