### ISSUE TITLE
Add api_version to keys.cfg

### ISSUE THREAD

**Issue by kim-borgen** [princeton-nlp/SWE-agent#73]
Need to specify api_version for Azure OpenAI deployments #16

**Comment by klieret** [comment]
Ah I see, it only relates to the PR! In that case I'll directly add it there!

**Comment by kim-borgen** [comment]
Well, there are probably more use cases to set an api_version for non azure models also 🤷

**Comment by klieret** [comment]
Since we addressed the immediate need for azure, let me close this. I'll leave it up to users of the other APIs to pull something like that in if they want to. Or we switch to another abstraction layer like litellm in the future to avoid having to handle this ourselves.
