### ISSUE TITLE
The utils directory is not included in the build artifacts.

### ISSUE THREAD

**Issue by won0-kim** [princeton-nlp/SWE-agent#741]
### Describe the issue

After the pip install, the utils directory is not included in the build artifacts.
I think it’s because the \_\_init\_\_.py does not exist in utils.

* there is no utils directory in `build/lib/sweagent`

![image](https://github.com/user-attachments/assets/a3159139-8f29-478c-b560-62bb42d8efe4)

**Comment by klieret** [comment]
Oh good catch! `swe-agent` currently isn't packaged well at all (because also `run.py` exists outside of the main thing), but let me already fix this
