### ISSUE TITLE
Environment fails to execute empty edit command

### ISSUE THREAD

**Issue by kamalojasv181** [princeton-nlp/SWE-agent#753]
### Describe the bug

Our agent gave a thought that it wanted to delete a function. So it gave an action `edit 16:26\nend_of_edit\n` . Now our environment is not able to execute the command, since it is not able to read anything in the `read_with_timeout_experimental ` and the container reboots.

### Steps/commands/code to Reproduce

I cannot provide the code for the agent since the work is unpublished, but we have made no change in the action space of SWE-agent or in the `SWEEnv` class . We are running our agent on the swe-bench-lite test instance_id `pylint-dev__pylint-7993`. 
```
python run.py --model_name gpt4o-mini --instance_filter pylint-dev__pylint-7993 --config_file config/default.yaml --per_instance_cost_limit 20.00 --skip_existing True --split test
```

### Error message/results

```
2024-09-01 09:40:50,180 ERROR Timeout reached while reading from subprocess.
2024-09-01 09:40:50,189 ERROR Read with timeout failed on input:
---
edit 16:26
end_of_edit

---
2024-09-01 09:40:50,195 WARNING Execution timed out. Attempting to interrupt process.
2024-09-01 09:40:50,314 INFO Communicating with container: echo 'interrupted'
2024-09-01 09:40:50,318 TRACE Input:
echo 'interrupted'
2024-09-01 09:40:50,318 INFO Communicating with container: /bin/bash -n <<'EOF'
echo 'interrupted'
EOF
```

### System Information

We have tried this issue on both MacOS and Ububtu 22.04

### Checklist

- [X] I'm running with the latest docker container/on the latest development version (this means running both `git pull` and `docker pull sweagent/swe-agent:latest`)
- [X] I have copied the full command/code that I ran (as text, not as screenshot!)
- [X] If applicable: I have copied the **full** log file/error message that was the result (as text, not as screenshot!)
- [X] I have enclosed code/log messages in triple backticks ([docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)) and clicked "Preview" to make sure it's displayed correctly.

**Comment by klieret** [comment]
I cannot reproduce this in `human` mode:

```
> create test
INFO     💭 THOUGHT (primary)

INFO     🎬 ACTION (primary)
         create test
INFO     🤖 MODEL INPUT
         [File: /__Users__fuchur__Documents__24__git_sync__swe-agent-test-repo/test (1 lines total)]
         1:
         (Open file: /__Users__fuchur__Documents__24__git_sync__swe-agent-test-repo/test)
         (Current directory: /__Users__fuchur__Documents__24__git_sync__swe-agent-test-repo)
         bash-$
> edit 1:1
... here
... are
... some
... lines
... end_of_edit
INFO     💭 THOUGHT (primary)

INFO     🎬 ACTION (primary)
         edit 1:1
         here
         are
         some
         lines
         end_of_edit
INFO     🤖 MODEL INPUT
         [File: /__Users__fuchur__Documents__24__git_sync__swe-agent-test-repo/test (4 lines total)]
         1:here
         2:are
         3:some
         4:lines
         File updated. Please review the changes and make sure they are correct (correct indentation, no duplicate lines, etc). Edit the file again if necessary.
         (Open file: /__Users__fuchur__Documents__24__git_sync__swe-agent-test-repo/test)
         (Current directory: /__Users__fuchur__Documents__24__git_sync__swe-agent-test-repo)
         bash-$
> edit 1:100
... end_of_edit
INFO     💭 THOUGHT (primary)

INFO     🎬 ACTION (primary)
         edit 1:100
         end_of_edit
INFO     🤖 MODEL INPUT
         [File: /__Users__fuchur__Documents__24__git_sync__swe-agent-test-repo/test (1 lines total)]
         1:
         File updated. Please review the changes and make sure they are correct (correct indentation, no duplicate lines, etc). Edit the file again if necessary.
         (Open file: /__Users__fuchur__Documents__24__git_sync__swe-agent-test-repo/test)
         (Current directory: /__Users__fuchur__Documents__24__git_sync__swe-agent-test-repo)
         bash-$
```

**Comment by klieret** [comment]
First, please try to use `--model human` and reproduce the bug with the modified SWE-agent.

In addition, could you locate your corresponding `.log` file and give me the corresponding lines? There we see the commands that are actually put into the shell and what happened.

In general, uou could also try with the legacy communication mode (see the [docs](https://princeton-nlp.github.io/SWE-agent/config/env/)), but it will be much slower. The "experimental" communicate is what we now use as default and I've seen relatively few hiccups.
