### ISSUE TITLE
Can we run this in local set-up? with local --data_path and --repo_path

### ISSUE THREAD

**Issue by buntys2010** [princeton-nlp/SWE-agent#761]
### Describe the issue

Does this work with local repo with path like
--data_path="./1.md"
--repo_path="./some_repo"

Or does it require a github link always?

I am trying below command

docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
  -e AZURE_OPENAI_API_KEY="" \
  -e AZURE_OPENAI_ENDPOINT="" \
  -e AZURE_OPENAI_DEPLOYMENT="" \
  -e AZURE_OPENAI_API_VERSION="" \
  -v "$(pwd)/sweagent/keys.cfg:/app/keys.cfg" \
  sweagent/swe-agent-run:latest \
  python run.py --image_name=sweagent/swe-agent:latest \
  --model azure:gpt4 \
  --data_path "/path/ai_store_problems/1.md" \
  --repo_path "/path/langflow" \
  --config_file config/default_from_url.yaml \
  --apply_patch_locally

I am getting error `ValueError: repo_path must be empty if running over multiple problem statements` 

I am actually trying single problem statement.

**Comment by klieret** [comment]
SWE-agent definitely works with local repositories/text files. I think the issue in your command might be that you are using the fully dockerized version, but you probably haven't copied the repository specified by `--repo_path` to the container. The error message is indeed probably misleading, I'll check if it gets triggered with a non-existing path. 

But also: The fully dockerized installation is only a fallback, please use the default installation from source if you can to avoid problems like this one.
