### ISSUE TITLE
Is there any plan to add more repo isntances (e.g. swe-bench train set cases) into the swe-agent framework?

### ISSUE THREAD

**Issue by adazhng** [princeton-nlp/SWE-agent#762]
### Describe the feature

support for swe-bench train dataset repository

### Potential Solutions

extending versioning automation 
currently only support for test dataset

**Comment by klieret** [comment]
I don't understand the question. SWE-bench is fully supported; you can load different datasets from `.json` files.

**Comment by adazhng** [comment]
> I don't understand the question. SWE-bench is fully supported; you can load different datasets from `.json` files.

I mean environment set up for swe-bench **training set**, since swe-agent needs the outcome from sandbox... 
I just find the same query in this link https://github.com/princeton-nlp/SWE-bench/issues/185
