### ISSUE TITLE
Ollama vision models?

### ISSUE THREAD

**Issue by emmettluzar** [princeton-nlp/SWE-agent#77]
Can I use an Ollama vision model for this? Is there any use or benefit to that? I'm not super familiar with this project yet but I'd like to try to use it for a MATLAB project, which requires a payed account so I was hoping it could use the MATLAB app on my computer or something and also see graphical results with an Ollama vision model. Is any of this possible to any degree? Thanks for the help.

**Comment by erkinalp** [comment]
matlab source code is text, and open source reimplementation, octave could be used

**Comment by emmettluzar** [comment]
Or maybe with a Matlab proxy? I heard about those but I'm not sure exactly how they work or how I'd integrate it with this project, and if I could, if swe could see the graphics

**Comment by erkinalp** [comment]
again, matlab source code is text, and you could use octave, the flagship open source matlab implementation, it can produce graphics, but lacks GUI

**Comment by klieret** [comment]
We do support Ollama (see #51 , #5 ), but I don't understand what Ollama _vision_ would be used for.
