### ISSUE TITLE
httpcore.ConnectError && httpx.ConnectError && git clone exception

### ISSUE THREAD

**Issue by wendianllw** [princeton-nlp/SWE-agent#781]
### Describe the issue

File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused
...
...
File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

The attachment contains the command and its output. 
[output.md](https://github.com/user-attachments/files/17124137/output.md)

Thanks!

**Comment by klieret** [comment]
Regarding the git error

```
RuntimeError: Failed to clone repository with fast method: hint: Using 'master' as the name for the initial branch. This default branch name

hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /pvlib__pvlib-python/.git/
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 3868 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
INFO     Beginning environment shutdown...                                      
Traceback (most recent call last):
  File "/app/sweagent/api/server.py", line 75, in run
    main.main()
  File "/app/run.py", line 397, in main
    raise e
  File "/app/run.py", line 381, in main
    self.run(index)
  File "/app/run.py", line 345, in run
    observation, info = self.env.reset(index)
  File "/app/sweagent/environment/swe_env.py", line 331, in reset
    self._copy_repo()
  File "/app/sweagent/environment/swe_env.py", line 264, in _copy_repo
    self.communicate_with_handling(
  File "/app/sweagent/environment/swe_env.py", line 798, in communicate_with_handling
    raise RuntimeError(msg)
RuntimeError: Failed to clone repository with fast method: hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /pvlib__pvlib-python/.git/
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 3868 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

I'd say that's an internet connection problem (?).

**Comment by wendianllw** [comment]
> Relevant bit seems to be
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
>     yield
>   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 236, in handle_request
>     resp = self._pool.handle_request(req)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
>     raise exc from None
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
>     response = connection.handle_request(
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
>     raise exc
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
>     stream = self._connect(request)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 122, in _connect
>     stream = self._network_backend.connect_tcp(**kwargs)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 213, in connect_tcp
>     sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
>   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc
> 
> ##### httpcore.ConnectError: [Errno 111] Connection refused
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/run.py", line 381, in main
>     self.run(index)
>   File "/app/run.py", line 365, in run
>     info, trajectory = self.agent.run(
>   File "/app/sweagent/agent/agents.py", line 812, in run
>     thought, action, output = self.forward(observation, env.get_available_actions(), state)
>   File "/app/sweagent/agent/agents.py", line 488, in forward
>     thought, action, output = self.forward_with_error_check(observation, state)
>   File "/app/sweagent/agent/agents.py", line 646, in forward_with_error_check
>     return self.check_format_and_requery(self.forward_model(observation, state))
>   File "/app/sweagent/agent/agents.py", line 548, in forward_model
>     return self.model.query(self.local_history)
>   File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 336, in wrapped_f
>     return copy(f, *args, **kw)
>   File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 475, in __call__
>     do = self.iter(retry_state=retry_state)
>   File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 376, in iter
>     result = action(retry_state)
>   File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 418, in exc_check
>     raise retry_exc.reraise()
>   File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 185, in reraise
>     raise self.last_attempt.result()
>   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
>     return self.__get_result()
>   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
>     raise self._exception
>   File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 478, in __call__
>     result = fn(*args, **kwargs)
>   File "/app/sweagent/agent/models.py", line 709, in query
>     response = self.client.chat(
>   File "/usr/local/lib/python3.9/site-packages/ollama/_client.py", line 236, in chat
>     return self._request_stream(
>   File "/usr/local/lib/python3.9/site-packages/ollama/_client.py", line 99, in _request_stream
>     return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
>   File "/usr/local/lib/python3.9/site-packages/ollama/_client.py", line 70, in _request
>     response = self._client.request(method, url, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 837, in request
>     return self.send(request, auth=auth, follow_redirects=follow_redirects)
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 926, in send
>     response = self._send_handling_auth(
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 954, in _send_handling_auth
>     response = self._send_handling_redirects(
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
>     response = self._send_single_request(request)
>   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1027, in _send_single_request
>     response = transport.handle_request(request)
>   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 236, in handle_request
>     resp = self._pool.handle_request(req)
>   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.ConnectError: [Errno 111] Connection refused
> ```
> 
> So this seems to be a problem with your `ollama` setup. There's a small bit of info [here](https://princeton-nlp.github.io/SWE-agent/usage/usage_faq/) about using llama

Okay, thank you. I'll check it out.
