### ISSUE TITLE
O1-preview and O1-mini support

### ISSUE THREAD

**Issue by AlexCuadron** [princeton-nlp/SWE-agent#785]
### Describe the feature

Is there a plan to add support for the new models from [OpenAI](https://platform.openai.com/docs/models/o1)? 
It currently requires a [Tier 4 API level](https://x.com/OpenAIDevs/status/1838611640201162807).

### Potential Solutions

Include the option to use o1-mini and o1-preview, but warn the user that this will only work if they have a Tier 5 API level.

**Comment by ofirpress** [comment]
contributions on this are welcome, this is on our list for sure
