### ISSUE TITLE
Add "Back to Top" Button

### ISSUE THREAD

**Issue by Ayushjhawar8** [princeton-nlp/SWE-agent#826]
### Describe the feature

The "Back to Top" button allows users to quickly return to the top of the page with one click. Currently, users need to scroll manually, which can be cumbersome on long pages. This feature would improve navigation and enhance user experience by making it easier to access the top of the page.

### Potential Solutions

- **Floating Button**: Positioned at the bottom right corner/middle for easy access.
- **ID for Topmost Image**: Add an ID to the topmost image on the page so that the button can directly link to it.

Sample Screenshot:
![image](https://github.com/user-attachments/assets/530c071c-6938-4b0d-b3b4-cb9d8f3b5b71)

- [x] Yes im ready to contribute towards this issue

**Comment by klieret** [comment]
Thanks for the suggestion!

**Comment by Ayushjhawar8** [comment]
> @klieret Thanks for the suggestion!

no probs also you can add this same button in the readme at bottom with something like this
```
<div align="center" align-items: center;">
        <a href="#top">
            <img src="https://img.shields.io/badge/Back%20to%20Top-000000?style=for-the-badge&logo=github&logoColor=white" alt="Back to Top">
        </a>
</div>

```

and give id to any image at top

**Comment by klieret** [comment]
thanks, but let's keep it simple :)
