### ISSUE TITLE
SWE-agent trajectories on SWE-bench

### ISSUE THREAD

**Issue by felipemaiapolo** [princeton-nlp/SWE-agent#832]
### Describe the issue

Dear maintainers,

Thank you for the amazing work. I am using SWE-bench trajectories data in my research and I realized you made information like the cost and number of received/sent tokens public. My questions are the following:
1) Is there a way I can access (or compute) the cost and number of received/sent tokens per API call?
2) How is "total_cost" computed? I see very high numbers which vary from instance to instance

Thank you!

**Comment by klieret** [comment]
> Is there a way I can access (or compute) the cost and number of received/sent tokens per API call?

The cost calculations are in [models.py](https://github.com/princeton-nlp/SWE-agent/blob/main/sweagent/agent/models.py). Does that help? It's also displayed as log messages when running the agent (per call), so you can probably parse that. 

> How is "total_cost" computed? I see very high numbers which vary from instance to instance

Are you talking about the data in `APIStats`? 
You probably want to look at `instant_cost`. `total_cost` is essentially the cumulative `instance_cost` 


lmk if that answers your question (not sure if I understood you correctly)

**Comment by felipemaiapolo** [comment]
Hi Kilian,

Thank you for your help. 
1) Info per iteration. At the moment, I am not interested in the number itself than how it is computed. Right now, I am looking at three directories (from SWE-bench) inside "20240620_sweagent_claude3.5sonnet" and I see three folds: results, logs, and trajs. In trajs, there is one ".traj" per GitHub issue; in these files, I can only see the cost and token info for a full agent run. In the logs folder, I also see a file per GitHub but the cost and number of sent and received tokens do not seem to be there. Maybe I am missing something here?

2) Total cost. Now I understand it's cumulative, thank you!

**Comment by ofirpress** [comment]
You can view trajectories by following the instructions here: https://github.com/swe-bench/experiments?tab=readme-ov-file#viewing-logs-trajectories

**Comment by felipemaiapolo** [comment]
Hi Ofir,

The trajectories do not contain the information I am looking (cost and number of received/sent tokens per iteration). I was wondering if you have this info saved somewhere.

Best,
Felipe

**Comment by ofirpress** [comment]
Hi @felipemaiapolo -
Ah ok- I'm not sure if we still have that anywhere, maybe @john-b-yang or @carlosejimenez would know. You could also just compute it based on the trajectories.

**Comment by felipemaiapolo** [comment]
Hi Ofir,

Thank you for your response. I could compute it from trajectories. Would you mind giving me the instructions to do that? Thank you!
