### ISSUE TITLE
Running SWE-agent with SWE-bench Dataset

### ISSUE THREAD

**Issue by ramsey-coding** [princeton-nlp/SWE-agent#88]
SWE-agent Team!

Great work, congrats.

I am attempting to run the SWE-agent on the SWE-bench dataset and have encountered some challenges in understanding the process. I see some scripts in the repository at [this link](https://github.com/princeton-nlp/SWE-agent/tree/main/scripts), which seem relevant to what I am trying to achieve.

However, the documentation does not outline the steps for executing these scripts, collecting patches, running them against the test suites, and then gathering the results. Could you please provide help me?

- Executing Scripts: how to run the scripts located in the scripts directory.
- Collecting Patches: how to collect patches generated by SWE-agent.
- Running Test Suites: run these patches against test suites within the SWE-bench dataset.
- Gathering Results: how to best collect and interpret the results from the test runs.

Thanks!

**Comment by ramsey-coding** [comment]
@klieret really appreciate for looking into it. I would really appreciate your help with this issue. At least how to run it against the SWE-Bench.

**Comment by ofirpress** [comment]
After we post the preprint @john-b-yang and @carlosejimenez will provide all the details for running SWE-agent on SWE-bench.

**Comment by ofirpress** [comment]
Pushing this up so we remember to get to it. 

We should make it so there's one command that runs SWE-agent on SWE-bench and executes evaluation.

**Comment by klieret** [comment]
Hi @ramsey-coding is this still an issue? I think that https://princeton-nlp.github.io/SWE-agent/usage/benchmarking/ shows how to do everything. 

> We should make it so there's one command that runs SWE-agent on SWE-bench and executes evaluation.

@ofirpress  So far it is only two commands. I think this is a good solution. Trying to bring these two very different steps together will make things more complicated (tons of command line options to be handled, stronger dependency on SWE-bench changes). Don't think this is worth the added convenience (+ harder for users to debug if things fail).

**Comment by ofirpress** [comment]
SGTM! 2 commands is totally fine. Thank you!
