### ISSUE TITLE
Local LLM inference support 

### ISSUE THREAD

**Issue by sanbuphy** [princeton-nlp/SWE-agent#91]
I want to ask if SWE support use local llm inference backend? because gpt4 will be expensive in multiturn comversation, maybe we can use the local llm to instead of online llm invoke

**Comment by carlosejimenez** [comment]
We currently have the option to use ollama as a model backend. You can do this with the `--host_url` and use `--model_name` arguments. `host_url` defaults to `localhost:11434` which is the default ollama host url when running locally, but this can also point to a remote server running at `ip-addr:port`. `model_name` is the model name from ollama, prefixed with `ollama:` (e.g. `ollama:mixtral`). We haven't tested SWE-agent using models smaller than Claude 3 Opus and GPT-4 turbo, so your results may vary.

You can see all models hostable with ollama at: https://ollama.com/library

I'm closing this for now, but please open if you don't think this resolves your issue.
