### ISSUE TITLE
Docker fails to clone repo on Windows

### ISSUE THREAD

**Issue by steventangbc** [princeton-nlp/SWE-agent#94]
```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock 
  -e GITHUB_TOKEN="" 
  -e OPENAI_API_KEY="" 
  sweagent/swe-agent-run:latest \
  python run.py --image_name=sweagent/swe-agent:latest
```

![image](https://github.com/princeton-nlp/SWE-agent/assets/94030446/a10880c5-fe34-4210-9d7f-d6e5426a60ef)

![image](https://github.com/princeton-nlp/SWE-agent/assets/94030446/25815b28-bd08-41d3-abca-55ae113266a5)

**Comment by klieret** [comment]
Can you please copy the error message as text?

**Comment by klieret** [comment]
I think I can reproduce this if I supply an incorrect github token. Can you try putting in your `GITHUB_TOKEN` in the above command?

**Comment by steventangbc** [comment]
docker run --rm -it -v //var/run/docker.sock:/var/run/docker.sock -v C:\Users\Alyssa\Documents\SWE-agent sweagent/swe-agent-run:latest python run.py --image_name=sweagent/swe-agent:latest --model_name gpt4 --data_path https://github.com/pvlib/pvlib-python/issues/1603 --config_file config/default_from_url.yaml  --skip_existing=False

...

Traceback (most recent call last):
  File "/app/run.py", line 288, in <module>
    main(args)
  File "/app/run.py", line 90, in main
    env = SWEEnv(args.environment)
  File "/app/sweagent/environment/swe_env.py", line 102, in __init__
    self.data = get_instances(self.data_path, self.args.base_commit, self.args.split, token=self.token)
  File "/app/sweagent/environment/utils.py", line 344, in get_instances
    issue = api.issues.get(owner, repo, issue_number)
  File "/usr/local/lib/python3.9/site-packages/ghapi/core.py", line 62, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/usr/local/lib/python3.9/site-packages/ghapi/core.py", line 121, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=debug, return_headers=True,
  File "/usr/local/lib/python3.9/site-packages/fastcore/net.py", line 218, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/usr/local/lib/python3.9/site-packages/fastcore/net.py", line 119, in urlread
    if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp, msg=e.msg) from None
fastcore.net.HTTP401UnauthorizedError: HTTP Error 401: Unauthorized
====Error Body====
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}

I have verified that my GITHUB_TOKEN is correct. Would Windows use different syntax to configure keys.cfg than Linux? I followed the instructions from the readme and setup the keys.cfg file as follows:

GITHUB_TOKEN: 'xxx'
OPENAI_API_KEY: 'xxx'

I tried putting keys.cfg in the same folder as SWE-agent as well as the directory containing SWE-agent.

**Comment by steventangbc** [comment]
Putting in my GITHUB_TOKEN did not change anything. I included both my GITHUB_TOKEN and OPENAI_API_KEY in my original command but redacted them in this issue.

**Comment by steventangbc** [comment]
Update: I tried again using the updated instructions —

docker run --rm -it -v path:/app -v //var/run/docker.sock:/var/run/docker.sock sweagent/swe-agent-run:latest python run.py --image_name=sweagent/swe-agent:latest --model_name gpt4 --data_path https://github.com/pvlib/pvlib-python/issues/1603 --config_file config/default_from_url.yaml --skip_existing=False

...and it works!

**Comment by klieret** [comment]
That's great to hear! I realized that environment variables weren't properly used (#111), so that's probably why you saw the failure before with the fully dockerized solution.
