### ISSUE TITLE
Not working with the latest updated

### ISSUE THREAD

**Issue by PierrunoYT** [princeton-nlp/SWE-agent#96]
![grafik](https://github.com/princeton-nlp/SWE-agent/assets/95778421/64e68742-28b3-4feb-b639-1c070a994b88)

**Comment by klieret** [comment]
Can you run `./setup.sh` again? This might be because we changed the name of the docker container.

**Comment by klieret** [comment]
Also please _copy_ your error messages instead of screenshots
