### ISSUE TITLE
Wrong image name in the setup.sh file

### ISSUE THREAD

**Issue by Alexia-I** [princeton-nlp/SWE-agent#97]
Hi, I just found a small problem in your setup.sh file, line 11 and line 14. 
```
docker build -t sweagent/swe-agent:latest --build-arg MINICONDA_URL=https://repo.anaconda.com/miniconda/Miniconda3-py39_23.11.0-1-Linux-x86_64.sh -f docker/swe.Dockerfile .

```
Basically, if you follow this command, you would encounter the error below:
```
File "/Users/yanghaowen/anaconda3/envs/swe-agent/lib/python3.9/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.43/containers/swe-agent-7f56d92532/json: Not Found ("No such container: swe-agent-7f56d92532")
```
It appears that the previous command generated an image with the wrong name, preventing the agent from creating the container from the image. 
Changing the image name from `sweagent/swe-agent` to 'swe-agent' will solve it.

**Comment by klieret** [comment]
Just to double check, are you running on the latest version of the repository? Can you run `./setup.sh` again?

I'm also confused about your error below. It looks like it's issued from the `docker` python API. What command are you running? The `run.py` one?

**Comment by klieret** [comment]
This was my mistake, the default image name in `run.py` should be `sweagent/swe-agent:latest` so it matches the name from `setup.sh`.

You can try it right away by adding `--image_name=sweagent/swe-agent:latest` or by pulling the latest version.

**Comment by Alexia-I** [comment]
Yeah I can confirm that the bug has been solved after changing the image name in `run.py`. Thank you.
